export const seedCategories = [
  { id: 'cat-8', name_nl: 'Voorgerechten', name_en: 'Starters', name_tr: 'Başlangıçlar', name_ar: 'مقبلات', sort_order: -1, active: true, icon: '' },
  { id: 'cat-7', name_nl: 'Menu Deals', name_en: 'Menu Deals', name_tr: 'Menü Fırsatları', name_ar: 'عروض المنيو', sort_order: 0, active: true, icon: '🎁' },
  { id: 'cat-9', name_nl: 'Lahmacun', name_en: 'Lahmacun', name_tr: 'Lahmacun', name_ar: 'لحم عجين', sort_order: 1, active: true, icon: '' },
  { id: 'cat-10', name_nl: 'Dürüm', name_en: 'Dürüm', name_tr: 'Dürüm', name_ar: 'دوروم', sort_order: 2, active: true, icon: '' },
  { id: 'cat-11', name_nl: 'Broodjes', name_en: 'Sandwiches', name_tr: 'Sandviçler', name_ar: 'سندويشات', sort_order: 3, active: true, icon: '' },
  { id: 'cat-12', name_nl: 'Schotels', name_en: 'Platters', name_tr: 'Tabaklar', name_ar: 'أطباق', sort_order: 4, active: true, icon: '' },
  { id: 'cat-13', name_nl: 'Kapsalons', name_en: 'Kapsalons', name_tr: 'Kapsalonlar', name_ar: 'كابسالون', sort_order: 5, active: true, icon: '' },
  { id: 'cat-14', name_nl: 'Kinderschotels', name_en: 'Kids Meals', name_tr: 'Çocuk Tabakları', name_ar: 'وجبات أطفال', sort_order: 6, active: true, icon: '' },
  { id: 'cat-15', name_nl: "Pizza's", name_en: 'Pizzas', name_tr: 'Pizzalar', name_ar: 'بيتزا', sort_order: 7, active: true, icon: '' },
  { id: 'cat-16', name_nl: 'Calzones', name_en: 'Calzones', name_tr: 'Kalzoneler', name_ar: 'كالزوني', sort_order: 8, active: true, icon: '' },
  { id: 'cat-17', name_nl: "Pasta's", name_en: 'Pastas', name_tr: 'Makarnalar', name_ar: 'معكرونة', sort_order: 9, active: true, icon: '' },
  { id: 'cat-18', name_nl: 'Patat', name_en: 'Fries', name_tr: 'Patates', name_ar: 'بطاطا', sort_order: 10, active: true, icon: '' },
  { id: 'cat-4', name_nl: 'Salades', name_en: 'Salads', name_tr: 'Salatalar', name_ar: 'سلطات', sort_order: 11, active: true, icon: '🥗' },
  { id: 'cat-19', name_nl: 'Dranken', name_en: 'Drinks', name_tr: 'İçecekler', name_ar: 'مشروبات', sort_order: 12, active: true, icon: '' },
  { id: 'cat-20', name_nl: "Extra's", name_en: 'Extras', name_tr: 'Ekstralar', name_ar: 'إضافات', sort_order: 13, active: true, icon: '' },
]

export const seedMenuItems = [
  {
    id: 'item-9',
    category_id: 'cat-4',
    name_nl: 'Turkse Hirtensalade',
    name_en: 'Turkish Shepherd Salad',
    name_tr: 'Türk Çoban Salatası',
    name_ar: 'سلطة الراعي التركية',
    description_nl: 'Verse tomaten, komkommer, paprika, rode ui, peterselie en citroendressing.',
    description_en: 'Fresh tomatoes, cucumber, bell pepper, red onion, parsley and lemon dressing.',
    description_tr: 'Taze domates, salatalık, biber, kırmızı soğan, maydanoz ve limon sosuyla.',
    description_ar: 'طماطم طازجة وخيار وفلفل وبصل أحمر وبقدونس وصلصة الليمون.',
    price: 6.50,
    image_url: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=800',
    preparation_time: 8,
    vegetarian: true,
    seasonal: false,
    sold_out: false,
    allergens: {},
    popular_count: 89,
    active: true,
  },
  {
    id: 'item-10',
    category_id: 'cat-4',
    name_nl: 'Halloumi Salade',
    name_en: 'Halloumi Salad',
    name_tr: 'Hellim Salatası',
    name_ar: 'سلطة الحلوم',
    description_nl: 'Gegrilde halloumi op een bed van gemengde groenten met granaatappelpitten en citroendressing.',
    description_en: 'Grilled halloumi on a bed of mixed greens with pomegranate seeds and lemon dressing.',
    description_tr: 'Nar taneleri ve limon sosu ile karışık yeşillikler üzerinde ızgara hellim.',
    description_ar: 'جبن الحلوم المشوي على طبقة من الخضروات المشكلة مع بذور الرمان وصلصة الليمون.',
    price: 9.00,
    image_url: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800',
    preparation_time: 10,
    vegetarian: true,
    seasonal: false,
    sold_out: false,
    allergens: { lactose: true },
    popular_count: 112,
    active: true,
  },
  {
    id: 'item-20',
    category_id: 'cat-4',
    name_nl: 'Hummus met Pita',
    name_en: 'Hummus with Pita',
    name_tr: 'Humus ve Pide',
    name_ar: 'حمص مع خبز البيتا',
    description_nl: 'Huisgemaakte hummus van kikkererwten met olijfolie, paprikapoeder en pita.',
    description_en: 'Homemade hummus from chickpeas with olive oil, paprika powder and pita.',
    description_tr: 'Zeytinyağı, kırmızı biber tozu ve pide ile nohuttan yapılan ev yapımı humus.',
    description_ar: 'حمص محلي الصنع من الحمص مع زيت الزيتون ومسحوق الفلفل الحلو وخبز البيتا.',
    price: 6.00,
    image_url: 'https://images.unsplash.com/photo-1571167530149-c1105da4c2c0?w=800',
    preparation_time: 5,
    vegetarian: true,
    seasonal: false,
    sold_out: false,
    allergens: { gluten: true, nuts: true },
    popular_count: 201,
    active: true,
  },
  {
    id: 'item-30',
    category_id: 'cat-8',
    name_nl: 'Turks brood met kruidenboter',
    name_en: 'Turkish bread with herb butter',
    name_tr: 'Otlu tereyağlı Türk ekmeği',
    name_ar: 'خبز تركي مع زبدة الأعشاب',
    description_nl: 'Vers gebakken Turks brood geserveerd met huisgemaakte kruidenboter.',
    description_en: 'Freshly baked Turkish bread served with homemade herb butter.',
    description_tr: 'Ev yapımı otlu tereyağı ile servis edilen taze pişirilmiş Türk ekmeği.',
    description_ar: 'خبز تركي طازج مقدم مع زبدة الأعشاب محلية الصنع.',
    price: 5.00,
    image_url: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800',
    preparation_time: 8,
    vegetarian: true,
    seasonal: false,
    sold_out: false,
    allergens: { gluten: true, lactose: true },
    popular_count: 180,
    active: true,
  },
  {
    id: 'item-31',
    category_id: 'cat-8',
    name_nl: 'Cacik',
    name_en: 'Cacik',
    name_tr: 'Cacık',
    name_ar: 'جاجيك',
    description_nl: 'Yoghurtsalade met komkommer, knoflook en peterselie.',
    description_en: 'Yoghurt salad with cucumber, garlic and parsley.',
    description_tr: 'Salatalık, sarımsak ve maydanozlu yoğurt salatası.',
    description_ar: 'سلطة الزبادي مع الخيار والثوم والبقدونس.',
    price: 4.50,
    image_url: 'https://images.unsplash.com/photo-1571167530149-c1105da4c2c0?w=800',
    preparation_time: 5,
    vegetarian: true,
    seasonal: false,
    sold_out: false,
    allergens: { lactose: true },
    popular_count: 142,
    active: true,
  },
  {
    id: 'item-32',
    category_id: 'cat-8',
    name_nl: 'Funghi trifolati',
    name_en: 'Funghi trifolati',
    name_tr: 'Funghi trifolati',
    name_ar: 'فطر مقلي بزبدة الأعشاب',
    description_nl: 'Gebakken champignons in kruidenboter, met roomsaus.',
    description_en: 'Sautéed mushrooms in herb butter, with cream sauce.',
    description_tr: 'Otlu tereyağında sote mantar, krema soslu.',
    description_ar: 'فطر مقلي في زبدة الأعشاب مع صلصة الكريمة.',
    price: 7.00,
    image_url: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800',
    preparation_time: 10,
    vegetarian: true,
    seasonal: false,
    sold_out: false,
    allergens: { lactose: true },
    popular_count: 98,
    active: true,
  },
  {
    id: 'item-26',
    category_id: 'cat-7',
    name_nl: 'Broodje Doner + Patat + Cola',
    name_en: 'Döner Roll + Fries + Cola',
    name_tr: 'Döner Ekmek + Patates + Kola',
    name_ar: 'خبز دونر + بطاطا + كولا',
    description_nl: 'Sappig döner in een zacht broodje, knapperige patat en een blikje Cola.',
    description_en: 'Juicy döner in a soft roll, crispy fries and a can of Cola.',
    description_tr: 'Yumuşak ekmekte sulu döner, çıtır patates ve Cola kutusu.',
    description_ar: 'دونر طري في خبز ناعم مع بطاطا مقلية وعلبة كولا.',
    price: 11.00,
    image_url: 'https://images.unsplash.com/photo-1561758033-d89a9ad46330?w=800',
    preparation_time: 12,
    vegetarian: false,
    seasonal: false,
    sold_out: false,
    allergens: { gluten: true },
    popular_count: 310,
    active: true,
  },
  {
    id: 'item-27',
    category_id: 'cat-7',
    name_nl: 'Durum + Patat + Cola',
    name_en: 'Durum + Fries + Cola',
    name_tr: 'Dürüm + Patates + Kola',
    name_ar: 'دوروم + بطاطا + كولا',
    description_nl: 'Gevulde durum wrap met döner of kip, knapperige patat en een blikje Cola.',
    description_en: 'Filled durum wrap with döner or chicken, crispy fries and a can of Cola.',
    description_tr: 'Döner veya tavuklu dolu dürüm, çıtır patates ve Cola kutusu.',
    description_ar: 'دوروم مليء بالدونر أو الدجاج مع بطاطا مقلية وعلبة كولا.',
    price: 11.50,
    image_url: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800',
    preparation_time: 12,
    vegetarian: false,
    seasonal: false,
    sold_out: false,
    allergens: { gluten: true },
    popular_count: 278,
    active: true,
  },
  {
    id: 'item-28',
    category_id: 'cat-7',
    name_nl: 'Lahmacun + Patat + Cola',
    name_en: 'Lahmacun + Fries + Cola',
    name_tr: 'Lahmacun + Patates + Kola',
    name_ar: 'لحم عجين + بطاطا + كولا',
    description_nl: 'Knapperige Turkse lahmacun met gehakt en kruiden, knapperige patat en een blikje Cola.',
    description_en: 'Crispy Turkish lahmacun with minced meat and herbs, crispy fries and a can of Cola.',
    description_tr: 'Kıymalı ve baharatlı çıtır Türk lahmacunu, çıtır patates ve Cola kutusu.',
    description_ar: 'لحم عجين تركي مقرمش مع اللحم المفروم والأعشاب مع بطاطا مقلية وعلبة كولا.',
    price: 9.00,
    image_url: 'https://images.unsplash.com/photo-1574484284002-952d92456975?w=800',
    preparation_time: 15,
    vegetarian: false,
    seasonal: false,
    sold_out: false,
    allergens: { gluten: true },
    popular_count: 245,
    active: true,
  },
  {
    id: 'item-29',
    category_id: 'cat-7',
    name_nl: 'Schotel Doner + Cola',
    name_en: 'Döner Platter + Cola',
    name_tr: 'Döner Tabağı + Kola',
    name_ar: 'طبق دونر + كولا',
    description_nl: 'Royale dönerschotel met rijst of friet, salade, saus en een blikje Cola.',
    description_en: 'Generous döner platter with rice or fries, salad, sauce and a can of Cola.',
    description_tr: 'Pirinç veya patates, salata, sos ve Cola kutusu ile geniş döner tabağı.',
    description_ar: 'طبق دونر سخي مع الأرز أو البطاطا والسلطة والصلصة وعلبة كولا.',
    price: 14.50,
    image_url: 'https://images.unsplash.com/photo-1529006557810-274b9b2fc783?w=800',
    preparation_time: 15,
    vegetarian: false,
    seasonal: false,
    sold_out: false,
    allergens: { gluten: true },
    popular_count: 195,
    active: true,
  },
  {
    id: 'item-33',
    category_id: 'cat-4',
    name_nl: 'Gemengde salade',
    name_en: 'Mixed salad',
    name_tr: 'Karışık salata',
    name_ar: 'سلطة مشكلة',
    description_nl: 'Gemengde salade met fetakaas.',
    description_en: 'Mixed salad with feta cheese.',
    description_tr: 'Beyaz peynirli karışık salata.',
    description_ar: 'سلطة مشكلة مع جبن الفيتا.',
    price: 5.00,
    image_url: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800',
    preparation_time: 5,
    vegetarian: true,
    seasonal: false,
    sold_out: false,
    allergens: { lactose: true },
    popular_count: 130,
    active: true,
  },
  {
    id: 'item-34',
    category_id: 'cat-4',
    name_nl: 'Tonijn salade',
    name_en: 'Tuna salad',
    name_tr: 'Ton balıklı salata',
    name_ar: 'سلطة التونة',
    description_nl: 'Gemengde salade met tonijn.',
    description_en: 'Mixed salad with tuna.',
    description_tr: 'Ton balıklı karışık salata.',
    description_ar: 'سلطة مشكلة مع التونة.',
    price: 5.00,
    image_url: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=800',
    preparation_time: 5,
    vegetarian: false,
    seasonal: false,
    sold_out: false,
    allergens: { fish: true },
    popular_count: 95,
    active: true,
  },
  {
    id: 'item-35',
    category_id: 'cat-4',
    name_nl: 'Hawai salade',
    name_en: 'Hawaii salad',
    name_tr: 'Hawaii salatası',
    name_ar: 'سلطة هاواي',
    description_nl: 'Gemengde salade met ham en ananas.',
    description_en: 'Mixed salad with ham and pineapple.',
    description_tr: 'Jambonlu ve ananaslı karışık salata.',
    description_ar: 'سلطة مشكلة مع لحم الخنزير والأناناس.',
    price: 5.00,
    image_url: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800',
    preparation_time: 5,
    vegetarian: false,
    seasonal: false,
    sold_out: false,
    allergens: {},
    popular_count: 87,
    active: true,
  },
  {
    id: 'item-36',
    category_id: 'cat-4',
    name_nl: 'Coban salade',
    name_en: 'Coban salad',
    name_tr: 'Çoban salatası',
    name_ar: 'سلطة الراعي',
    description_nl: 'Tomaat, komkommer, ui, peterselie en Turkse peper.',
    description_en: 'Tomato, cucumber, onion, parsley and Turkish pepper.',
    description_tr: 'Domates, salatalık, soğan, maydanoz ve Türk biberi.',
    description_ar: 'طماطم وخيار وبصل وبقدونس وفلفل تركي.',
    price: 5.00,
    image_url: 'https://images.unsplash.com/photo-1529059997568-3d847b1154f0?w=800',
    preparation_time: 5,
    vegetarian: true,
    seasonal: false,
    sold_out: false,
    allergens: {},
    popular_count: 160,
    active: true,
  },
  {
    id: 'item-37',
    category_id: 'cat-9',
    name_nl: 'Lahmacun 1',
    name_en: 'Lahmacun 1',
    name_tr: 'Lahmacun 1',
    name_ar: 'لحم عجين 1',
    description_nl: 'Met salade.',
    description_en: 'With salad.',
    description_tr: 'Salatalı.',
    description_ar: 'مع السلطة.',
    price: 3.50,
    image_url: 'https://images.unsplash.com/photo-1574484284002-952d92456975?w=800',
    preparation_time: 12,
    vegetarian: false,
    seasonal: false,
    sold_out: false,
    allergens: { gluten: true },
    popular_count: 210,
    active: true,
  },
  {
    id: 'item-38',
    category_id: 'cat-9',
    name_nl: 'Lahmacun 2',
    name_en: 'Lahmacun 2',
    name_tr: 'Lahmacun 2',
    name_ar: 'لحم عجين 2',
    description_nl: 'Met kaas en salade.',
    description_en: 'With cheese and salad.',
    description_tr: 'Peynirli ve salatalı.',
    description_ar: 'مع الجبن والسلطة.',
    price: 5.00,
    image_url: 'https://images.unsplash.com/photo-1574484284002-952d92456975?w=800',
    preparation_time: 12,
    vegetarian: false,
    seasonal: false,
    sold_out: false,
    allergens: { gluten: true, lactose: true },
    popular_count: 175,
    active: true,
  },
  {
    id: 'item-39',
    category_id: 'cat-9',
    name_nl: 'Lahmacun 3',
    name_en: 'Lahmacun 3',
    name_tr: 'Lahmacun 3',
    name_ar: 'لحم عجين 3',
    description_nl: 'Met doner en kaas.',
    description_en: 'With döner and cheese.',
    description_tr: 'Dönerli ve peynirli.',
    description_ar: 'مع الدونر والجبن.',
    price: 6.00,
    image_url: 'https://images.unsplash.com/photo-1574484284002-952d92456975?w=800',
    preparation_time: 15,
    vegetarian: false,
    seasonal: false,
    sold_out: false,
    allergens: { gluten: true, lactose: true },
    popular_count: 230,
    active: true,
  },
  {
    id: 'item-40',
    category_id: 'cat-9',
    name_nl: 'Lahmacun 4',
    name_en: 'Lahmacun 4',
    name_tr: 'Lahmacun 4',
    name_ar: 'لحم عجين 4',
    description_nl: 'Met doner, kaas en salade.',
    description_en: 'With döner, cheese and salad.',
    description_tr: 'Dönerli, peynirli ve salatalı.',
    description_ar: 'مع الدونر والجبن والسلطة.',
    price: 6.50,
    image_url: 'https://images.unsplash.com/photo-1574484284002-952d92456975?w=800',
    preparation_time: 15,
    vegetarian: false,
    seasonal: false,
    sold_out: false,
    allergens: { gluten: true, lactose: true },
    popular_count: 260,
    active: true,
  },
  {
    id: 'item-41',
    category_id: 'cat-10',
    name_nl: 'Dürüm Döner',
    name_en: 'Dürüm Döner',
    name_tr: 'Dürüm Döner',
    name_ar: 'دوروم دونر',
    description_nl: 'Opgerolde tortilla met döner en verse groenten.',
    description_en: 'Rolled tortilla with döner and fresh vegetables.',
    description_tr: 'Döner ve taze sebzeli rulo tortilla.',
    description_ar: 'تورتيلا ملفوفة مع الدونر والخضروات الطازجة.',
    price: 7.00,
    image_url: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800',
    preparation_time: 10,
    vegetarian: false,
    seasonal: false,
    sold_out: false,
    allergens: { gluten: true },
    popular_count: 220,
    active: true,
  },
  {
    id: 'item-42',
    category_id: 'cat-10',
    name_nl: 'Dürüm met Kaas',
    name_en: 'Dürüm with Cheese',
    name_tr: 'Peynirli Dürüm',
    name_ar: 'دوروم بالجبن',
    description_nl: 'Opgerolde tortilla met döner, gesmolten kaas en verse groenten.',
    description_en: 'Rolled tortilla with döner, melted cheese and fresh vegetables.',
    description_tr: 'Döner, erimiş peynir ve taze sebzeli rulo tortilla.',
    description_ar: 'تورتيلا ملفوفة مع الدونر والجبن المذاب والخضروات الطازجة.',
    price: 7.50,
    image_url: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800',
    preparation_time: 10,
    vegetarian: false,
    seasonal: false,
    sold_out: false,
    allergens: { gluten: true, lactose: true },
    popular_count: 195,
    active: true,
  },
  {
    id: 'item-43',
    category_id: 'cat-10',
    name_nl: 'Dürüm Kipdöner',
    name_en: 'Dürüm Chicken Döner',
    name_tr: 'Tavuk Döner Dürüm',
    name_ar: 'دوروم دونر دجاج',
    description_nl: 'Opgerolde tortilla met kipdöner en verse groenten.',
    description_en: 'Rolled tortilla with chicken döner and fresh vegetables.',
    description_tr: 'Tavuk döner ve taze sebzeli rulo tortilla.',
    description_ar: 'تورتيلا ملفوفة مع دونر الدجاج والخضروات الطازجة.',
    price: 7.00,
    image_url: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800',
    preparation_time: 10,
    vegetarian: false,
    seasonal: false,
    sold_out: false,
    allergens: { gluten: true },
    popular_count: 210,
    active: true,
  },
  {
    id: 'item-44',
    category_id: 'cat-10',
    name_nl: 'Dürüm Kipfilet',
    name_en: 'Dürüm Chicken Fillet',
    name_tr: 'Tavuk Fileto Dürüm',
    name_ar: 'دوروم فيليه دجاج',
    description_nl: 'Opgerolde tortilla met gegrilde kipfilet en verse groenten.',
    description_en: 'Rolled tortilla with grilled chicken fillet and fresh vegetables.',
    description_tr: 'Izgara tavuk filetosu ve taze sebzeli rulo tortilla.',
    description_ar: 'تورتيلا ملفوفة مع فيليه الدجاج المشوي والخضروات الطازجة.',
    price: 8.00,
    image_url: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800',
    preparation_time: 12,
    vegetarian: false,
    seasonal: false,
    sold_out: false,
    allergens: { gluten: true },
    popular_count: 180,
    active: true,
  },
  {
    id: 'item-45',
    category_id: 'cat-10',
    name_nl: 'Dürüm Adana',
    name_en: 'Dürüm Adana',
    name_tr: 'Adana Dürüm',
    name_ar: 'دوروم أضنة',
    description_nl: 'Opgerolde tortilla met pittig gegrild gekruid gehakt en verse groenten.',
    description_en: 'Rolled tortilla with spicy grilled minced meat and fresh vegetables.',
    description_tr: 'Acı ızgara kıyma ve taze sebzeli rulo tortilla.',
    description_ar: 'تورتيلا ملفوفة مع اللحم المفروم الحار المشوي والخضروات الطازجة.',
    price: 8.00,
    image_url: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800',
    preparation_time: 12,
    vegetarian: false,
    seasonal: false,
    sold_out: false,
    allergens: { gluten: true },
    popular_count: 165,
    active: true,
  },
  {
    id: 'item-46',
    category_id: 'cat-10',
    name_nl: 'Dürüm Gezond',
    name_en: 'Dürüm Healthy',
    name_tr: 'Sağlıklı Dürüm',
    name_ar: 'دوروم صحي',
    description_nl: 'Opgerolde tortilla met gebakken ei, kaas, fetakaas en verse groenten.',
    description_en: 'Rolled tortilla with fried egg, cheese, feta and fresh vegetables.',
    description_tr: 'Sahanda yumurta, peynir, beyaz peynir ve taze sebzeli rulo tortilla.',
    description_ar: 'تورتيلا ملفوفة مع البيض المقلي والجبن وجبن الفيتا والخضروات الطازجة.',
    price: 5.50,
    image_url: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800',
    preparation_time: 10,
    vegetarian: true,
    seasonal: false,
    sold_out: false,
    allergens: { gluten: true, lactose: true, eggs: true },
    popular_count: 140,
    active: true,
  },
  {
    id: 'item-47',
    category_id: 'cat-10',
    name_nl: 'Dürüm Sis',
    name_en: 'Dürüm Sis',
    name_tr: 'Şiş Dürüm',
    name_ar: 'دوروم شيش',
    description_nl: 'Opgerolde tortilla met gegrild vlees van de sis en verse groenten.',
    description_en: 'Rolled tortilla with grilled skewer meat and fresh vegetables.',
    description_tr: 'Izgara şiş eti ve taze sebzeli rulo tortilla.',
    description_ar: 'تورتيلا ملفوفة مع لحم الشيش المشوي والخضروات الطازجة.',
    price: 8.00,
    image_url: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800',
    preparation_time: 12,
    vegetarian: false,
    seasonal: false,
    sold_out: false,
    allergens: { gluten: true },
    popular_count: 175,
    active: true,
  },
  {
    id: 'item-48',
    category_id: 'cat-11',
    name_nl: 'Broodje Döner',
    name_en: 'Döner Sandwich',
    name_tr: 'Döner Ekmek',
    name_ar: 'ساندويش دونر',
    description_nl: 'Gesneden kalfsdöner met verse groenten.',
    description_en: 'Sliced veal döner with fresh vegetables.',
    description_tr: 'Dilimlenmiş dana döner ve taze sebzeli ekmek.',
    description_ar: 'دونر عجل مشرح مع خضروات طازجة.',
    price: 6.00,
    image_url: 'https://images.unsplash.com/photo-1561758033-d89a9ad46330?w=800',
    preparation_time: 8,
    vegetarian: false,
    seasonal: false,
    sold_out: false,
    allergens: { gluten: true },
    popular_count: 280,
    active: true,
  },
  {
    id: 'item-49',
    category_id: 'cat-11',
    name_nl: 'Broodje Döner Speciaal',
    name_en: 'Döner Special Sandwich',
    name_tr: 'Özel Döner Ekmek',
    name_ar: 'ساندويش دونر سبيشيال',
    description_nl: 'Gesneden kalfsdöner met paprika, ui, champignons en verse groenten.',
    description_en: 'Sliced veal döner with bell pepper, onion, mushrooms and fresh vegetables.',
    description_tr: 'Dilimlenmiş dana döner, biber, soğan, mantar ve taze sebzeli ekmek.',
    description_ar: 'دونر عجل مشرح مع الفلفل والبصل والفطر والخضروات الطازجة.',
    price: 6.50,
    image_url: 'https://images.unsplash.com/photo-1561758033-d89a9ad46330?w=800',
    preparation_time: 10,
    vegetarian: false,
    seasonal: false,
    sold_out: false,
    allergens: { gluten: true },
    popular_count: 210,
    active: true,
  },
  {
    id: 'item-50',
    category_id: 'cat-11',
    name_nl: 'Broodje Kipdöner',
    name_en: 'Chicken Döner Sandwich',
    name_tr: 'Tavuk Döner Ekmek',
    name_ar: 'ساندويش دونر دجاج',
    description_nl: 'Gesneden kipdöner met verse groenten.',
    description_en: 'Sliced chicken döner with fresh vegetables.',
    description_tr: 'Dilimlenmiş tavuk döner ve taze sebzeli ekmek.',
    description_ar: 'دونر دجاج مشرح مع خضروات طازجة.',
    price: 6.00,
    image_url: 'https://images.unsplash.com/photo-1561758033-d89a9ad46330?w=800',
    preparation_time: 8,
    vegetarian: false,
    seasonal: false,
    sold_out: false,
    allergens: { gluten: true },
    popular_count: 265,
    active: true,
  },
  {
    id: 'item-51',
    category_id: 'cat-11',
    name_nl: 'Broodje Kipdöner Speciaal',
    name_en: 'Chicken Döner Special Sandwich',
    name_tr: 'Özel Tavuk Döner Ekmek',
    name_ar: 'ساندويش دونر دجاج سبيشيال',
    description_nl: 'Gesneden kipdöner met paprika, ui, champignons en verse groenten.',
    description_en: 'Sliced chicken döner with bell pepper, onion, mushrooms and fresh vegetables.',
    description_tr: 'Dilimlenmiş tavuk döner, biber, soğan, mantar ve taze sebzeli ekmek.',
    description_ar: 'دونر دجاج مشرح مع الفلفل والبصل والفطر والخضروات الطازجة.',
    price: 6.50,
    image_url: 'https://images.unsplash.com/photo-1561758033-d89a9ad46330?w=800',
    preparation_time: 10,
    vegetarian: false,
    seasonal: false,
    sold_out: false,
    allergens: { gluten: true },
    popular_count: 190,
    active: true,
  },
  {
    id: 'item-52',
    category_id: 'cat-11',
    name_nl: 'Broodje Kipfilet',
    name_en: 'Chicken Fillet Sandwich',
    name_tr: 'Tavuk Fileto Ekmek',
    name_ar: 'ساندويش فيليه دجاج',
    description_nl: 'Gegrilde stukjes kipfilet met verse groenten.',
    description_en: 'Grilled chicken fillet pieces with fresh vegetables.',
    description_tr: 'Izgara tavuk fileto parçaları ve taze sebzeli ekmek.',
    description_ar: 'قطع فيليه دجاج مشوية مع خضروات طازجة.',
    price: 7.50,
    image_url: 'https://images.unsplash.com/photo-1561758033-d89a9ad46330?w=800',
    preparation_time: 12,
    vegetarian: false,
    seasonal: false,
    sold_out: false,
    allergens: { gluten: true },
    popular_count: 220,
    active: true,
  },
  {
    id: 'item-53',
    category_id: 'cat-11',
    name_nl: 'Broodje Kipfilet Speciaal',
    name_en: 'Chicken Fillet Special Sandwich',
    name_tr: 'Özel Tavuk Fileto Ekmek',
    name_ar: 'ساندويش فيليه دجاج سبيشيال',
    description_nl: 'Gegrilde stukjes kipfilet met paprika, ui, champignons en verse groenten.',
    description_en: 'Grilled chicken fillet pieces with bell pepper, onion, mushrooms and fresh vegetables.',
    description_tr: 'Izgara tavuk fileto, biber, soğan, mantar ve taze sebzeli ekmek.',
    description_ar: 'قطع فيليه دجاج مشوية مع الفلفل والبصل والفطر والخضروات الطازجة.',
    price: 8.00,
    image_url: 'https://images.unsplash.com/photo-1561758033-d89a9ad46330?w=800',
    preparation_time: 12,
    vegetarian: false,
    seasonal: false,
    sold_out: false,
    allergens: { gluten: true },
    popular_count: 175,
    active: true,
  },
  {
    id: 'item-54',
    category_id: 'cat-11',
    name_nl: 'Broodje Sis',
    name_en: 'Sis Sandwich',
    name_tr: 'Şiş Ekmek',
    name_ar: 'ساندويش شيش',
    description_nl: 'Gegrilde stukjes kalfsvlees van de spies met verse groenten.',
    description_en: 'Grilled veal pieces from the skewer with fresh vegetables.',
    description_tr: 'Şişten ızgara dana parçaları ve taze sebzeli ekmek.',
    description_ar: 'قطع عجل مشوية من الشيش مع خضروات طازجة.',
    price: 7.50,
    image_url: 'https://images.unsplash.com/photo-1561758033-d89a9ad46330?w=800',
    preparation_time: 12,
    vegetarian: false,
    seasonal: false,
    sold_out: false,
    allergens: { gluten: true },
    popular_count: 160,
    active: true,
  },
  {
    id: 'item-55',
    category_id: 'cat-11',
    name_nl: 'Broodje Köfte',
    name_en: 'Köfte Sandwich',
    name_tr: 'Köfte Ekmek',
    name_ar: 'ساندويش كفتة',
    description_nl: 'Gekruid gegrild gehakt met verse groenten.',
    description_en: 'Seasoned grilled minced meat with fresh vegetables.',
    description_tr: 'Baharatlı ızgara kıyma ve taze sebzeli ekmek.',
    description_ar: 'لحم مفروم مشوي متبل مع خضروات طازجة.',
    price: 7.50,
    image_url: 'https://images.unsplash.com/photo-1561758033-d89a9ad46330?w=800',
    preparation_time: 12,
    vegetarian: false,
    seasonal: false,
    sold_out: false,
    allergens: { gluten: true },
    popular_count: 185,
    active: true,
  },
  {
    id: 'item-56',
    category_id: 'cat-11',
    name_nl: 'Broodje Falafel',
    name_en: 'Falafel Sandwich',
    name_tr: 'Falafel Ekmek',
    name_ar: 'ساندويش فلافل',
    description_nl: 'Krokante falafelballetjes van kikkererwten met verse groenten.',
    description_en: 'Crispy chickpea falafel balls with fresh vegetables.',
    description_tr: 'Çıtır nohut falafel topları ve taze sebzeli ekmek.',
    description_ar: 'كرات الفلافل المقرمشة من الحمص مع خضروات طازجة.',
    price: 5.50,
    image_url: 'https://images.unsplash.com/photo-1561758033-d89a9ad46330?w=800',
    preparation_time: 10,
    vegetarian: true,
    seasonal: false,
    sold_out: false,
    allergens: { gluten: true },
    popular_count: 130,
    active: true,
  },
  {
    id: 'item-57',
    category_id: 'cat-11',
    name_nl: 'Broodje Gezond',
    name_en: 'Healthy Sandwich',
    name_tr: 'Sağlıklı Ekmek',
    name_ar: 'ساندويش صحي',
    description_nl: 'Gebakken ei, kaas, fetakaas en verse groenten.',
    description_en: 'Fried egg, cheese, feta and fresh vegetables.',
    description_tr: 'Sahanda yumurta, peynir, beyaz peynir ve taze sebzeli ekmek.',
    description_ar: 'بيض مقلي وجبن وجبن فيتا وخضروات طازجة.',
    price: 5.50,
    image_url: 'https://images.unsplash.com/photo-1561758033-d89a9ad46330?w=800',
    preparation_time: 8,
    vegetarian: true,
    seasonal: false,
    sold_out: false,
    allergens: { gluten: true, lactose: true, eggs: true },
    popular_count: 145,
    active: true,
  },
  {
    id: 'item-58',
    category_id: 'cat-11',
    name_nl: 'Broodje Kaas',
    name_en: 'Cheese Sandwich',
    name_tr: 'Peynirli Ekmek',
    name_ar: 'ساندويش جبن',
    description_nl: 'Gesmolten kaas.',
    description_en: 'Melted cheese.',
    description_tr: 'Erimiş peynirli ekmek.',
    description_ar: 'جبن مذاب.',
    price: 4.50,
    image_url: 'https://images.unsplash.com/photo-1561758033-d89a9ad46330?w=800',
    preparation_time: 6,
    vegetarian: true,
    seasonal: false,
    sold_out: false,
    allergens: { gluten: true, lactose: true },
    popular_count: 110,
    active: true,
  },
  {
    id: 'item-59',
    category_id: 'cat-11',
    name_nl: 'Broodje Ham Kaas',
    name_en: 'Ham Cheese Sandwich',
    name_tr: 'Jambon Peynirli Ekmek',
    name_ar: 'ساندويش جبن وهام',
    description_nl: 'Ham en gesmolten kaas.',
    description_en: 'Ham and melted cheese.',
    description_tr: 'Jambon ve erimiş peynirli ekmek.',
    description_ar: 'هام وجبن مذاب.',
    price: 5.00,
    image_url: 'https://images.unsplash.com/photo-1561758033-d89a9ad46330?w=800',
    preparation_time: 6,
    vegetarian: false,
    seasonal: false,
    sold_out: false,
    allergens: { gluten: true, lactose: true },
    popular_count: 125,
    active: true,
  },
  {
    id: 'item-60',
    category_id: 'cat-11',
    name_nl: 'Broodje Sucuk',
    name_en: 'Sucuk Sandwich',
    name_tr: 'Sucuklu Ekmek',
    name_ar: 'ساندويش سجق',
    description_nl: 'Gegrilde Turkse knoflookworst.',
    description_en: 'Grilled Turkish garlic sausage.',
    description_tr: 'Izgara Türk sucuğu ekmeği.',
    description_ar: 'سجق تركي بالثوم مشوي.',
    price: 5.00,
    image_url: 'https://images.unsplash.com/photo-1561758033-d89a9ad46330?w=800',
    preparation_time: 8,
    vegetarian: false,
    seasonal: false,
    sold_out: false,
    allergens: { gluten: true },
    popular_count: 155,
    active: true,
  },
  {
    id: 'item-61',
    category_id: 'cat-12',
    name_nl: 'Schotel Döner',
    name_en: 'Döner Platter',
    name_tr: 'Döner Tabağı',
    name_ar: 'طبق دونر',
    description_nl: 'Gesneden kalfsdöner.',
    description_en: 'Sliced veal döner.',
    description_tr: 'Dilimlenmiş dana döner.',
    description_ar: 'دونر عجل مشرح.',
    price: 13.00,
    image_url: 'https://images.unsplash.com/photo-1529006557810-274b9b2fc783?w=800',
    preparation_time: 15,
    vegetarian: false,
    seasonal: false,
    sold_out: false,
    allergens: { gluten: true },
    popular_count: 240,
    active: true,
  },
  {
    id: 'item-62',
    category_id: 'cat-12',
    name_nl: 'Schotel Döner Speciaal',
    name_en: 'Döner Special Platter',
    name_tr: 'Özel Döner Tabağı',
    name_ar: 'طبق دونر سبيشيال',
    description_nl: 'Kalfsdöner met paprika, ui en champignons.',
    description_en: 'Veal döner with bell pepper, onion and mushrooms.',
    description_tr: 'Biber, soğan ve mantarlı dana döner.',
    description_ar: 'دونر عجل مع الفلفل والبصل والفطر.',
    price: 13.50,
    image_url: 'https://images.unsplash.com/photo-1529006557810-274b9b2fc783?w=800',
    preparation_time: 15,
    vegetarian: false,
    seasonal: false,
    sold_out: false,
    allergens: { gluten: true },
    popular_count: 190,
    active: true,
  },
  {
    id: 'item-63',
    category_id: 'cat-12',
    name_nl: 'Schotel Kipdöner',
    name_en: 'Chicken Döner Platter',
    name_tr: 'Tavuk Döner Tabağı',
    name_ar: 'طبق دونر دجاج',
    description_nl: 'Gesneden kipdöner.',
    description_en: 'Sliced chicken döner.',
    description_tr: 'Dilimlenmiş tavuk döner.',
    description_ar: 'دونر دجاج مشرح.',
    price: 13.00,
    image_url: 'https://images.unsplash.com/photo-1529006557810-274b9b2fc783?w=800',
    preparation_time: 15,
    vegetarian: false,
    seasonal: false,
    sold_out: false,
    allergens: { gluten: true },
    popular_count: 220,
    active: true,
  },
  {
    id: 'item-64',
    category_id: 'cat-12',
    name_nl: 'Schotel Kipdöner Speciaal',
    name_en: 'Chicken Döner Special Platter',
    name_tr: 'Özel Tavuk Döner Tabağı',
    name_ar: 'طبق دونر دجاج سبيشيال',
    description_nl: 'Kipdöner met paprika, ui en champignons.',
    description_en: 'Chicken döner with bell pepper, onion and mushrooms.',
    description_tr: 'Biber, soğan ve mantarlı tavuk döner.',
    description_ar: 'دونر دجاج مع الفلفل والبصل والفطر.',
    price: 13.50,
    image_url: 'https://images.unsplash.com/photo-1529006557810-274b9b2fc783?w=800',
    preparation_time: 15,
    vegetarian: false,
    seasonal: false,
    sold_out: false,
    allergens: { gluten: true },
    popular_count: 175,
    active: true,
  },
  {
    id: 'item-65',
    category_id: 'cat-12',
    name_nl: 'Schotel Kipfilet',
    name_en: 'Chicken Fillet Platter',
    name_tr: 'Tavuk Fileto Tabağı',
    name_ar: 'طبق فيليه دجاج',
    description_nl: 'Gegrilde stukjes kipfilet.',
    description_en: 'Grilled chicken fillet pieces.',
    description_tr: 'Izgara tavuk fileto parçaları.',
    description_ar: 'قطع فيليه دجاج مشوية.',
    price: 15.50,
    image_url: 'https://images.unsplash.com/photo-1529006557810-274b9b2fc783?w=800',
    preparation_time: 18,
    vegetarian: false,
    seasonal: false,
    sold_out: false,
    allergens: { gluten: true },
    popular_count: 200,
    active: true,
  },
  {
    id: 'item-66',
    category_id: 'cat-12',
    name_nl: 'Schotel Kipfilet Speciaal',
    name_en: 'Chicken Fillet Special Platter',
    name_tr: 'Özel Tavuk Fileto Tabağı',
    name_ar: 'طبق فيليه دجاج سبيشيال',
    description_nl: 'Gegrilde kipfilet met paprika, ui en champignons.',
    description_en: 'Grilled chicken fillet with bell pepper, onion and mushrooms.',
    description_tr: 'Biber, soğan ve mantarlı ızgara tavuk fileto.',
    description_ar: 'فيليه دجاج مشوي مع الفلفل والبصل والفطر.',
    price: 16.00,
    image_url: 'https://images.unsplash.com/photo-1529006557810-274b9b2fc783?w=800',
    preparation_time: 18,
    vegetarian: false,
    seasonal: false,
    sold_out: false,
    allergens: { gluten: true },
    popular_count: 165,
    active: true,
  },
  {
    id: 'item-67',
    category_id: 'cat-12',
    name_nl: 'Schotel Sis',
    name_en: 'Sis Platter',
    name_tr: 'Şiş Tabağı',
    name_ar: 'طبق شيش',
    description_nl: 'Gegrilde stukjes kalfsvlees van de spies.',
    description_en: 'Grilled veal pieces from the skewer.',
    description_tr: 'Şişten ızgara dana parçaları.',
    description_ar: 'قطع عجل مشوية من الشيش.',
    price: 17.00,
    image_url: 'https://images.unsplash.com/photo-1529006557810-274b9b2fc783?w=800',
    preparation_time: 20,
    vegetarian: false,
    seasonal: false,
    sold_out: false,
    allergens: { gluten: true },
    popular_count: 155,
    active: true,
  },
  {
    id: 'item-68',
    category_id: 'cat-12',
    name_nl: 'Schotel Iskender',
    name_en: 'Iskender Platter',
    name_tr: 'Iskender Tabağı',
    name_ar: 'طبق اسكندر',
    description_nl: 'Kalfsdöner op brood met tomatensaus, botersaus en yoghurt.',
    description_en: 'Veal döner on bread with tomato sauce, butter sauce and yoghurt.',
    description_tr: 'Ekmek üzerinde dana döner, domates sosu, tereyağı sosu ve yoğurt.',
    description_ar: 'دونر عجل على الخبز مع صلصة الطماطم وصلصة الزبدة والزبادي.',
    price: 16.00,
    image_url: 'https://images.unsplash.com/photo-1529006557810-274b9b2fc783?w=800',
    preparation_time: 18,
    vegetarian: false,
    seasonal: false,
    sold_out: false,
    allergens: { gluten: true, lactose: true },
    popular_count: 210,
    active: true,
  },
  {
    id: 'item-69',
    category_id: 'cat-12',
    name_nl: 'Schotel Izgara Köfte',
    name_en: 'Izgara Köfte Platter',
    name_tr: 'Izgara Köfte Tabağı',
    name_ar: 'طبق كفتة مشوية',
    description_nl: '5 stuks gekruid gegrild gehakt.',
    description_en: '5 pieces of seasoned grilled minced meat.',
    description_tr: '5 adet baharatlı ızgara köfte.',
    description_ar: '5 قطع لحم مفروم متبل مشوي.',
    price: 17.50,
    image_url: 'https://images.unsplash.com/photo-1529006557810-274b9b2fc783?w=800',
    preparation_time: 20,
    vegetarian: false,
    seasonal: false,
    sold_out: false,
    allergens: { gluten: true },
    popular_count: 180,
    active: true,
  },
  {
    id: 'item-70',
    category_id: 'cat-12',
    name_nl: 'Schotel Izgara Pirzola',
    name_en: 'Izgara Pirzola Platter',
    name_tr: 'Izgara Pirzola Tabağı',
    name_ar: 'طبق ضلع مشوي',
    description_nl: '4 stuks gegrilde koteletten.',
    description_en: '4 grilled lamb chops.',
    description_tr: '4 adet ızgara pirzola.',
    description_ar: '4 قطع ضلع مشوي.',
    price: 19.50,
    image_url: 'https://images.unsplash.com/photo-1529006557810-274b9b2fc783?w=800',
    preparation_time: 22,
    vegetarian: false,
    seasonal: false,
    sold_out: false,
    allergens: {},
    popular_count: 140,
    active: true,
  },
  {
    id: 'item-71',
    category_id: 'cat-12',
    name_nl: 'Schotel Yogurtlu Kebab',
    name_en: 'Yogurtlu Kebab Platter',
    name_tr: 'Yoğurtlu Kebab Tabağı',
    name_ar: 'طبق كباب بالزبادي',
    description_nl: 'Gegrild gehakt met groenten, geserveerd met yoghurt.',
    description_en: 'Grilled minced meat with vegetables, served with yoghurt.',
    description_tr: 'Sebzeli ızgara kıyma, yoğurt ile servis edilir.',
    description_ar: 'لحم مفروم مشوي مع خضروات، يُقدم مع الزبادي.',
    price: 19.50,
    image_url: 'https://images.unsplash.com/photo-1529006557810-274b9b2fc783?w=800',
    preparation_time: 20,
    vegetarian: false,
    seasonal: false,
    sold_out: false,
    allergens: { gluten: true, lactose: true },
    popular_count: 135,
    active: true,
  },
  {
    id: 'item-72',
    category_id: 'cat-12',
    name_nl: 'Schotel Adana Kebab',
    name_en: 'Adana Kebab Platter',
    name_tr: 'Adana Kebab Tabağı',
    name_ar: 'طبق كباب أضنة',
    description_nl: '2 spiezen pittig gekruid gehakt van de grill.',
    description_en: '2 skewers of spicy seasoned minced meat from the grill.',
    description_tr: '2 şiş acı baharatlı ızgara kıyma.',
    description_ar: 'شيشان من اللحم المفروم الحار المتبل من الشواية.',
    price: 19.00,
    image_url: 'https://images.unsplash.com/photo-1529006557810-274b9b2fc783?w=800',
    preparation_time: 20,
    vegetarian: false,
    seasonal: false,
    sold_out: false,
    allergens: { gluten: true },
    popular_count: 160,
    active: true,
  },
  {
    id: 'item-73',
    category_id: 'cat-12',
    name_nl: 'Schotel Orman Kebab',
    name_en: 'Orman Kebab Platter',
    name_tr: 'Orman Kebab Tabağı',
    name_ar: 'طبق كباب الغابة',
    description_nl: 'Kalfsvlees met champignons, paprika en ui in tomaten- of roomsaus.',
    description_en: 'Veal with mushrooms, bell pepper and onion in tomato or cream sauce.',
    description_tr: 'Domates veya krema sosunda mantar, biber ve soğanlı dana eti.',
    description_ar: 'عجل مع الفطر والفلفل والبصل في صلصة الطماطم أو الكريمة.',
    price: 17.50,
    image_url: 'https://images.unsplash.com/photo-1529006557810-274b9b2fc783?w=800',
    preparation_time: 20,
    vegetarian: false,
    seasonal: false,
    sold_out: false,
    allergens: { gluten: true, lactose: true },
    popular_count: 145,
    active: true,
  },
  {
    id: 'item-74',
    category_id: 'cat-12',
    name_nl: 'Schotel Sac Kavurma',
    name_en: 'Sac Kavurma Platter',
    name_tr: 'Saç Kavurma Tabağı',
    name_ar: 'طبق ساج كافورما',
    description_nl: 'Kalfsvlees met gebakken groenten uit de Turkse wok.',
    description_en: 'Veal with sautéed vegetables from the Turkish wok.',
    description_tr: 'Türk sacında sote sebzeli dana eti.',
    description_ar: 'عجل مع خضروات مقلية من المقلاة التركية.',
    price: 19.00,
    image_url: 'https://images.unsplash.com/photo-1529006557810-274b9b2fc783?w=800',
    preparation_time: 20,
    vegetarian: false,
    seasonal: false,
    sold_out: false,
    allergens: { gluten: true },
    popular_count: 150,
    active: true,
  },
  {
    id: 'item-75',
    category_id: 'cat-12',
    name_nl: 'Schotel Mix',
    name_en: 'Mix Platter',
    name_tr: 'Karışık Tabak',
    name_ar: 'طبق مشكل',
    description_nl: 'Döner, kipfilet, sis, köfte en kotelet.',
    description_en: 'Döner, chicken fillet, sis, köfte and chop.',
    description_tr: 'Döner, tavuk fileto, şiş, köfte ve pirzola.',
    description_ar: 'دونر وفيليه دجاج وشيش وكفتة وضلع.',
    price: 21.00,
    image_url: 'https://images.unsplash.com/photo-1529006557810-274b9b2fc783?w=800',
    preparation_time: 25,
    vegetarian: false,
    seasonal: false,
    sold_out: false,
    allergens: { gluten: true },
    popular_count: 185,
    active: true,
  },
  {
    id: 'item-76',
    category_id: 'cat-12',
    name_nl: 'Schotel Falafel',
    name_en: 'Falafel Platter',
    name_tr: 'Falafel Tabağı',
    name_ar: 'طبق فلافل',
    description_nl: 'Krokante falafel met verse groenten.',
    description_en: 'Crispy falafel with fresh vegetables.',
    description_tr: 'Taze sebzeli çıtır falafel.',
    description_ar: 'فلافل مقرمشة مع خضروات طازجة.',
    price: 12.00,
    image_url: 'https://images.unsplash.com/photo-1529006557810-274b9b2fc783?w=800',
    preparation_time: 15,
    vegetarian: true,
    seasonal: false,
    sold_out: false,
    allergens: { gluten: true },
    popular_count: 120,
    active: true,
  },
  {
    id: 'item-77',
    category_id: 'cat-12',
    name_nl: 'Schotel Beyti Kebab',
    name_en: 'Beyti Kebab Platter',
    name_tr: 'Beyti Kebab Tabağı',
    name_ar: 'طبق بيتي كباب',
    description_nl: 'Opgerold gehakt in tortilla met tomatensaus en botersaus.',
    description_en: 'Rolled minced meat in tortilla with tomato sauce and butter sauce.',
    description_tr: 'Domates sosu ve tereyağı sosu ile tortillada sarılmış kıyma.',
    description_ar: 'لحم مفروم ملفوف في تورتيلا مع صلصة الطماطم وصلصة الزبدة.',
    price: 16.50,
    image_url: 'https://images.unsplash.com/photo-1529006557810-274b9b2fc783?w=800',
    preparation_time: 18,
    vegetarian: false,
    seasonal: false,
    sold_out: false,
    allergens: { gluten: true, lactose: true },
    popular_count: 170,
    active: true,
  },
  {
    id: 'item-78',
    category_id: 'cat-12',
    name_nl: 'Schotel Miniko',
    name_en: 'Miniko Platter',
    name_tr: 'Miniko Tabağı',
    name_ar: 'طبق مينيكو',
    description_nl: 'Kipfilet met champignons in romige saus.',
    description_en: 'Chicken fillet with mushrooms in creamy sauce.',
    description_tr: 'Kremamsı soslu mantar ve tavuk fileto.',
    description_ar: 'فيليه دجاج مع الفطر في صلصة كريمية.',
    price: 15.00,
    image_url: 'https://images.unsplash.com/photo-1529006557810-274b9b2fc783?w=800',
    preparation_time: 18,
    vegetarian: false,
    seasonal: false,
    sold_out: false,
    allergens: { gluten: true, lactose: true },
    popular_count: 145,
    active: true,
  },
  {
    id: 'item-79',
    category_id: 'cat-13',
    name_nl: 'Kapsalon Döner Klein',
    name_en: 'Kapsalon Döner Small',
    name_tr: 'Kapsalon Döner Küçük',
    name_ar: 'كابسالون دونر صغير',
    description_nl: 'Döner met friet, kaas en salade uit de oven.',
    description_en: 'Döner with fries, cheese and salad from the oven.',
    description_tr: 'Fırından döner, patates, peynir ve salata.',
    description_ar: 'دونر مع البطاطا والجبن والسلطة من الفرن.',
    price: 7.00,
    image_url: 'https://images.unsplash.com/photo-1561758033-d89a9ad46330?w=800',
    preparation_time: 15,
    vegetarian: false,
    seasonal: false,
    sold_out: false,
    allergens: { gluten: true, lactose: true },
    popular_count: 260,
    active: true,
  },
  {
    id: 'item-80',
    category_id: 'cat-13',
    name_nl: 'Kapsalon Kipdöner Klein',
    name_en: 'Kapsalon Chicken Döner Small',
    name_tr: 'Kapsalon Tavuk Döner Küçük',
    name_ar: 'كابسالون دونر دجاج صغير',
    description_nl: 'Kipdöner met friet, kaas en salade uit de oven.',
    description_en: 'Chicken döner with fries, cheese and salad from the oven.',
    description_tr: 'Fırından tavuk döner, patates, peynir ve salata.',
    description_ar: 'دونر دجاج مع البطاطا والجبن والسلطة من الفرن.',
    price: 7.00,
    image_url: 'https://images.unsplash.com/photo-1561758033-d89a9ad46330?w=800',
    preparation_time: 15,
    vegetarian: false,
    seasonal: false,
    sold_out: false,
    allergens: { gluten: true, lactose: true },
    popular_count: 245,
    active: true,
  },
  {
    id: 'item-81',
    category_id: 'cat-13',
    name_nl: 'Kapsalon Döner Groot',
    name_en: 'Kapsalon Döner Large',
    name_tr: 'Kapsalon Döner Büyük',
    name_ar: 'كابسالون دونر كبير',
    description_nl: 'Döner met friet, kaas en salade uit de oven.',
    description_en: 'Döner with fries, cheese and salad from the oven.',
    description_tr: 'Fırından döner, patates, peynir ve salata.',
    description_ar: 'دونر مع البطاطا والجبن والسلطة من الفرن.',
    price: 9.00,
    image_url: 'https://images.unsplash.com/photo-1561758033-d89a9ad46330?w=800',
    preparation_time: 15,
    vegetarian: false,
    seasonal: false,
    sold_out: false,
    allergens: { gluten: true, lactose: true },
    popular_count: 300,
    active: true,
  },
  {
    id: 'item-82',
    category_id: 'cat-13',
    name_nl: 'Kapsalon Kipdöner Groot',
    name_en: 'Kapsalon Chicken Döner Large',
    name_tr: 'Kapsalon Tavuk Döner Büyük',
    name_ar: 'كابسالون دونر دجاج كبير',
    description_nl: 'Kipdöner met friet, kaas en salade uit de oven.',
    description_en: 'Chicken döner with fries, cheese and salad from the oven.',
    description_tr: 'Fırından tavuk döner, patates, peynir ve salata.',
    description_ar: 'دونر دجاج مع البطاطا والجبن والسلطة من الفرن.',
    price: 9.00,
    image_url: 'https://images.unsplash.com/photo-1561758033-d89a9ad46330?w=800',
    preparation_time: 15,
    vegetarian: false,
    seasonal: false,
    sold_out: false,
    allergens: { gluten: true, lactose: true },
    popular_count: 280,
    active: true,
  },
  {
    id: 'item-83',
    category_id: 'cat-13',
    name_nl: 'Kapsalon Speciaal',
    name_en: 'Kapsalon Special',
    name_tr: 'Özel Kapsalon',
    name_ar: 'كابسالون سبيشيال',
    description_nl: 'Döner en kipdöner met friet, kaas en salade uit de oven.',
    description_en: 'Döner and chicken döner with fries, cheese and salad from the oven.',
    description_tr: 'Fırından döner ve tavuk döner, patates, peynir ve salata.',
    description_ar: 'دونر ودونر دجاج مع البطاطا والجبن والسلطة من الفرن.',
    price: 10.50,
    image_url: 'https://images.unsplash.com/photo-1561758033-d89a9ad46330?w=800',
    preparation_time: 18,
    vegetarian: false,
    seasonal: false,
    sold_out: false,
    allergens: { gluten: true, lactose: true },
    popular_count: 220,
    active: true,
  },
  {
    id: 'item-84',
    category_id: 'cat-13',
    name_nl: 'Kapsalon met Rijst',
    name_en: 'Kapsalon with Rice',
    name_tr: 'Pirinçli Kapsalon',
    name_ar: 'كابسالون مع الأرز',
    description_nl: 'Keuze uit döner of kipdöner met rijst, kaas en salade.',
    description_en: 'Choice of döner or chicken döner with rice, cheese and salad.',
    description_tr: 'Döner veya tavuk döner seçeneğiyle pirinç, peynir ve salata.',
    description_ar: 'اختيار دونر أو دونر دجاج مع الأرز والجبن والسلطة.',
    price: 9.50,
    image_url: 'https://images.unsplash.com/photo-1561758033-d89a9ad46330?w=800',
    preparation_time: 15,
    vegetarian: false,
    seasonal: false,
    sold_out: false,
    allergens: { gluten: true, lactose: true },
    popular_count: 195,
    active: true,
  },
  {
    id: 'item-85',
    category_id: 'cat-13',
    name_nl: 'Kapsalon Kipfilet Groot',
    name_en: 'Kapsalon Chicken Fillet Large',
    name_tr: 'Kapsalon Tavuk Fileto Büyük',
    name_ar: 'كابسالون فيليه دجاج كبير',
    description_nl: 'Gegrilde kipfilet met friet, kaas en salade uit de oven.',
    description_en: 'Grilled chicken fillet with fries, cheese and salad from the oven.',
    description_tr: 'Fırından ızgara tavuk fileto, patates, peynir ve salata.',
    description_ar: 'فيليه دجاج مشوي مع البطاطا والجبن والسلطة من الفرن.',
    price: 13.50,
    image_url: 'https://images.unsplash.com/photo-1561758033-d89a9ad46330?w=800',
    preparation_time: 18,
    vegetarian: false,
    seasonal: false,
    sold_out: false,
    allergens: { gluten: true, lactose: true },
    popular_count: 160,
    active: true,
  },
  {
    id: 'item-86',
    category_id: 'cat-13',
    name_nl: 'Kapsalon Kipfilet Klein',
    name_en: 'Kapsalon Chicken Fillet Small',
    name_tr: 'Kapsalon Tavuk Fileto Küçük',
    name_ar: 'كابسالون فيليه دجاج صغير',
    description_nl: 'Gegrilde kipfilet met friet, kaas en salade uit de oven.',
    description_en: 'Grilled chicken fillet with fries, cheese and salad from the oven.',
    description_tr: 'Fırından ızgara tavuk fileto, patates, peynir ve salata.',
    description_ar: 'فيليه دجاج مشوي مع البطاطا والجبن والسلطة من الفرن.',
    price: 9.50,
    image_url: 'https://images.unsplash.com/photo-1561758033-d89a9ad46330?w=800',
    preparation_time: 18,
    vegetarian: false,
    seasonal: false,
    sold_out: false,
    allergens: { gluten: true, lactose: true },
    popular_count: 175,
    active: true,
  },
  {
    id: 'item-87',
    category_id: 'cat-14',
    name_nl: 'Kinderschotel Döner',
    name_en: 'Kids Döner Meal',
    name_tr: 'Çocuk Döner Tabağı',
    name_ar: 'وجبة أطفال دونر',
    description_nl: 'Minischotel met döner, friet en salade.',
    description_en: 'Mini platter with döner, fries and salad.',
    description_tr: 'Döner, patates ve salatalı mini tabak.',
    description_ar: 'طبق صغير مع الدونر والبطاطا والسلطة.',
    price: 8.00,
    image_url: 'https://images.unsplash.com/photo-1561758033-d89a9ad46330?w=800',
    preparation_time: 12,
    vegetarian: false,
    seasonal: false,
    sold_out: false,
    allergens: { gluten: true },
    popular_count: 150,
    active: true,
  },
  {
    id: 'item-88',
    category_id: 'cat-14',
    name_nl: 'Kinderschotel Kipnuggets',
    name_en: 'Kids Chicken Nuggets Meal',
    name_tr: 'Çocuk Nugget Tabağı',
    name_ar: 'وجبة أطفال ناجيتس',
    description_nl: 'Kipnuggets met friet en salade.',
    description_en: 'Chicken nuggets with fries and salad.',
    description_tr: 'Patates ve salatalı tavuk nugget.',
    description_ar: 'ناجيتس دجاج مع البطاطا والسلطة.',
    price: 8.00,
    image_url: 'https://images.unsplash.com/photo-1562967914-608f82629710?w=800',
    preparation_time: 12,
    vegetarian: false,
    seasonal: false,
    sold_out: false,
    allergens: { gluten: true },
    popular_count: 165,
    active: true,
  },
  {
    id: 'item-89',
    category_id: 'cat-15',
    name_nl: 'Margherita',
    name_en: 'Margherita',
    name_tr: 'Margherita',
    name_ar: 'مارغريتا',
    description_nl: 'Klassieke pizza met kaas.',
    description_en: 'Classic pizza with cheese.',
    description_tr: 'Klasik peynirli pizza.',
    description_ar: 'بيتزا كلاسيكية بالجبن.',
    price: 10.00,
    image_url: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800',
    preparation_time: 20,
    vegetarian: true,
    seasonal: false,
    sold_out: false,
    allergens: { gluten: true, lactose: true },
    popular_count: 210,
    active: true,
  },
  {
    id: 'item-90',
    category_id: 'cat-15',
    name_nl: 'Feta',
    name_en: 'Feta',
    name_tr: 'Feta',
    name_ar: 'فيتا',
    description_nl: 'Met olijven en fetakaas.',
    description_en: 'With olives and feta cheese.',
    description_tr: 'Zeytin ve beyaz peynirli.',
    description_ar: 'مع الزيتون وجبن الفيتا.',
    price: 10.00,
    image_url: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800',
    preparation_time: 20,
    vegetarian: true,
    seasonal: false,
    sold_out: false,
    allergens: { gluten: true, lactose: true },
    popular_count: 165,
    active: true,
  },
  {
    id: 'item-91',
    category_id: 'cat-15',
    name_nl: 'Funghi',
    name_en: 'Funghi',
    name_tr: 'Funghi',
    name_ar: 'فونغي',
    description_nl: 'Met champignons.',
    description_en: 'With mushrooms.',
    description_tr: 'Mantarlı.',
    description_ar: 'مع الفطر.',
    price: 10.00,
    image_url: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800',
    preparation_time: 20,
    vegetarian: true,
    seasonal: false,
    sold_out: false,
    allergens: { gluten: true, lactose: true },
    popular_count: 155,
    active: true,
  },
  {
    id: 'item-92',
    category_id: 'cat-15',
    name_nl: 'Vegetariana',
    name_en: 'Vegetariana',
    name_tr: 'Vejetaryen',
    name_ar: 'نباتية',
    description_nl: 'Met gemengde groenten.',
    description_en: 'With mixed vegetables.',
    description_tr: 'Karışık sebzeli.',
    description_ar: 'مع خضروات مشكلة.',
    price: 10.00,
    image_url: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800',
    preparation_time: 20,
    vegetarian: true,
    seasonal: false,
    sold_out: false,
    allergens: { gluten: true, lactose: true },
    popular_count: 145,
    active: true,
  },
  {
    id: 'item-93',
    category_id: 'cat-15',
    name_nl: 'Quattro Formaggi',
    name_en: 'Quattro Formaggi',
    name_tr: 'Dört Peynirli',
    name_ar: 'أربعة جبن',
    description_nl: 'Met vier soorten kaas.',
    description_en: 'With four types of cheese.',
    description_tr: 'Dört çeşit peynirli.',
    description_ar: 'مع أربعة أنواع من الجبن.',
    price: 10.00,
    image_url: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800',
    preparation_time: 20,
    vegetarian: true,
    seasonal: false,
    sold_out: false,
    allergens: { gluten: true, lactose: true },
    popular_count: 180,
    active: true,
  },
  {
    id: 'item-94',
    category_id: 'cat-15',
    name_nl: 'Capricciosa',
    name_en: 'Capricciosa',
    name_tr: 'Kapriçyoza',
    name_ar: 'كابريتشوزا',
    description_nl: 'Met champignons, artisjok, tonijn en ansjovis.',
    description_en: 'With mushrooms, artichoke, tuna and anchovies.',
    description_tr: 'Mantar, enginar, ton balığı ve hamsi ile.',
    description_ar: 'مع الفطر والخرشوف والتونة والأنشوجة.',
    price: 10.00,
    image_url: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800',
    preparation_time: 20,
    vegetarian: false,
    seasonal: false,
    sold_out: false,
    allergens: { gluten: true, lactose: true, fish: true },
    popular_count: 140,
    active: true,
  },
  {
    id: 'item-95',
    category_id: 'cat-15',
    name_nl: 'Tonno',
    name_en: 'Tonno',
    name_tr: 'Tonno',
    name_ar: 'تونة',
    description_nl: 'Met tonijn, ui en paprika.',
    description_en: 'With tuna, onion and bell pepper.',
    description_tr: 'Ton balığı, soğan ve biberli.',
    description_ar: 'مع التونة والبصل والفلفل.',
    price: 10.00,
    image_url: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800',
    preparation_time: 20,
    vegetarian: false,
    seasonal: false,
    sold_out: false,
    allergens: { gluten: true, lactose: true, fish: true },
    popular_count: 160,
    active: true,
  },
  {
    id: 'item-96',
    category_id: 'cat-15',
    name_nl: 'Frutti di Mare',
    name_en: 'Frutti di Mare',
    name_tr: 'Deniz Mahsulleri',
    name_ar: 'ثمار البحر',
    description_nl: 'Met gemengde vissoorten.',
    description_en: 'With mixed seafood.',
    description_tr: 'Karışık deniz ürünleri ile.',
    description_ar: 'مع مأكولات بحرية مشكلة.',
    price: 10.00,
    image_url: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800',
    preparation_time: 20,
    vegetarian: false,
    seasonal: false,
    sold_out: false,
    allergens: { gluten: true, lactose: true, fish: true },
    popular_count: 130,
    active: true,
  },
  {
    id: 'item-97',
    category_id: 'cat-15',
    name_nl: 'Quattro Stagioni',
    name_en: 'Quattro Stagioni',
    name_tr: 'Dört Mevsim',
    name_ar: 'أربعة فصول',
    description_nl: 'Met ham, salami, champignons en paprika.',
    description_en: 'With ham, salami, mushrooms and bell pepper.',
    description_tr: 'Jambon, salam, mantar ve biberli.',
    description_ar: 'مع الهام والسلامي والفطر والفلفل.',
    price: 10.00,
    image_url: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800',
    preparation_time: 20,
    vegetarian: false,
    seasonal: false,
    sold_out: false,
    allergens: { gluten: true, lactose: true },
    popular_count: 175,
    active: true,
  },
  {
    id: 'item-98',
    category_id: 'cat-15',
    name_nl: 'Con Pollo',
    name_en: 'Con Pollo',
    name_tr: 'Tavuklu',
    name_ar: 'بالدجاج',
    description_nl: 'Met kipshoarma, paprika en ui.',
    description_en: 'With chicken shawarma, bell pepper and onion.',
    description_tr: 'Tavuk şavarma, biber ve soğanlı.',
    description_ar: 'مع شاورما الدجاج والفلفل والبصل.',
    price: 10.00,
    image_url: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800',
    preparation_time: 20,
    vegetarian: false,
    seasonal: false,
    sold_out: false,
    allergens: { gluten: true, lactose: true },
    popular_count: 190,
    active: true,
  },
  {
    id: 'item-99',
    category_id: 'cat-15',
    name_nl: 'Döner',
    name_en: 'Döner',
    name_tr: 'Dönerli',
    name_ar: 'دونر',
    description_nl: 'Met döner.',
    description_en: 'With döner.',
    description_tr: 'Dönerli.',
    description_ar: 'مع الدونر.',
    price: 10.00,
    image_url: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800',
    preparation_time: 20,
    vegetarian: false,
    seasonal: false,
    sold_out: false,
    allergens: { gluten: true, lactose: true },
    popular_count: 220,
    active: true,
  },
  {
    id: 'item-100',
    category_id: 'cat-15',
    name_nl: 'Döner Speciaal',
    name_en: 'Döner Special',
    name_tr: 'Özel Dönerli',
    name_ar: 'دونر سبيشيال',
    description_nl: 'Met döner, paprika, ui en champignons.',
    description_en: 'With döner, bell pepper, onion and mushrooms.',
    description_tr: 'Döner, biber, soğan ve mantarlı.',
    description_ar: 'مع الدونر والفلفل والبصل والفطر.',
    price: 10.00,
    image_url: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800',
    preparation_time: 20,
    vegetarian: false,
    seasonal: false,
    sold_out: false,
    allergens: { gluten: true, lactose: true },
    popular_count: 200,
    active: true,
  },
  {
    id: 'item-101',
    category_id: 'cat-15',
    name_nl: 'Mozaik',
    name_en: 'Mozaik',
    name_tr: 'Mozaik',
    name_ar: 'موزاييك',
    description_nl: 'Met döner, groenten, worst en ei.',
    description_en: 'With döner, vegetables, sausage and egg.',
    description_tr: 'Döner, sebze, sosis ve yumurtalı.',
    description_ar: 'مع الدونر والخضروات والنقانق والبيض.',
    price: 10.00,
    image_url: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800',
    preparation_time: 20,
    vegetarian: false,
    seasonal: false,
    sold_out: false,
    allergens: { gluten: true, lactose: true, eggs: true },
    popular_count: 245,
    active: true,
  },
  {
    id: 'item-102',
    category_id: 'cat-15',
    name_nl: 'Tandoori',
    name_en: 'Tandoori',
    name_tr: 'Tandoori',
    name_ar: 'تندوري',
    description_nl: 'Met döner en kipshoarma.',
    description_en: 'With döner and chicken shawarma.',
    description_tr: 'Döner ve tavuk şavarmali.',
    description_ar: 'مع الدونر وشاورما الدجاج.',
    price: 10.00,
    image_url: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800',
    preparation_time: 20,
    vegetarian: false,
    seasonal: false,
    sold_out: false,
    allergens: { gluten: true, lactose: true },
    popular_count: 185,
    active: true,
  },
  {
    id: 'item-103',
    category_id: 'cat-15',
    name_nl: 'Etna',
    name_en: 'Etna',
    name_tr: 'Etna',
    name_ar: 'إتنا',
    description_nl: 'Met ham, salami en kipshoarma.',
    description_en: 'With ham, salami and chicken shawarma.',
    description_tr: 'Jambon, salam ve tavuk şavarmalı.',
    description_ar: 'مع الهام والسلامي وشاورما الدجاج.',
    price: 10.00,
    image_url: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800',
    preparation_time: 20,
    vegetarian: false,
    seasonal: false,
    sold_out: false,
    allergens: { gluten: true, lactose: true },
    popular_count: 155,
    active: true,
  },
  {
    id: 'item-104',
    category_id: 'cat-15',
    name_nl: 'Salami',
    name_en: 'Salami',
    name_tr: 'Salamlı',
    name_ar: 'سلامي',
    description_nl: 'Met salami.',
    description_en: 'With salami.',
    description_tr: 'Salamlı.',
    description_ar: 'مع السلامي.',
    price: 10.00,
    image_url: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800',
    preparation_time: 20,
    vegetarian: false,
    seasonal: false,
    sold_out: false,
    allergens: { gluten: true, lactose: true },
    popular_count: 150,
    active: true,
  },
  {
    id: 'item-105',
    category_id: 'cat-15',
    name_nl: 'Prosciutto',
    name_en: 'Prosciutto',
    name_tr: 'Jambon',
    name_ar: 'بروشوتو',
    description_nl: 'Met ham.',
    description_en: 'With ham.',
    description_tr: 'Jambon ile.',
    description_ar: 'مع الهام.',
    price: 10.00,
    image_url: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800',
    preparation_time: 20,
    vegetarian: false,
    seasonal: false,
    sold_out: false,
    allergens: { gluten: true, lactose: true },
    popular_count: 145,
    active: true,
  },
  {
    id: 'item-106',
    category_id: 'cat-15',
    name_nl: 'Hawai',
    name_en: 'Hawaii',
    name_tr: 'Hawaii',
    name_ar: 'هاواي',
    description_nl: 'Met ham en ananas.',
    description_en: 'With ham and pineapple.',
    description_tr: 'Jambon ve ananaslı.',
    description_ar: 'مع الهام والأناناس.',
    price: 10.00,
    image_url: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800',
    preparation_time: 20,
    vegetarian: false,
    seasonal: false,
    sold_out: false,
    allergens: { gluten: true, lactose: true },
    popular_count: 170,
    active: true,
  },
  {
    id: 'item-107',
    category_id: 'cat-15',
    name_nl: 'Harderwijk',
    name_en: 'Harderwijk',
    name_tr: 'Harderwijk',
    name_ar: 'هاردرويك',
    description_nl: 'Met döner, tonijn en paprika, afgemaakt met salade en knoflooksaus.',
    description_en: 'With döner, tuna and bell pepper, finished with salad and garlic sauce.',
    description_tr: 'Döner, ton balığı ve biber, salata ve sarımsaklı sos ile tamamlanmış.',
    description_ar: 'مع الدونر والتونة والفلفل، مكمل بالسلطة وصلصة الثوم.',
    price: 10.00,
    image_url: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800',
    preparation_time: 20,
    vegetarian: false,
    seasonal: false,
    sold_out: false,
    allergens: { gluten: true, lactose: true, fish: true },
    popular_count: 195,
    active: true,
  },
  {
    id: 'item-108',
    category_id: 'cat-16',
    name_nl: 'Calzone',
    name_en: 'Calzone',
    name_tr: 'Kalzone',
    name_ar: 'كالزوني',
    description_nl: 'Met ham, salami en groenten.',
    description_en: 'With ham, salami and vegetables.',
    description_tr: 'Jambon, salam ve sebzeli.',
    description_ar: 'مع الهام والسلامي والخضروات.',
    price: 10.00,
    image_url: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800',
    preparation_time: 22,
    vegetarian: false,
    seasonal: false,
    sold_out: false,
    allergens: { gluten: true, lactose: true },
    popular_count: 160,
    active: true,
  },
  {
    id: 'item-109',
    category_id: 'cat-16',
    name_nl: 'Calzone Bolognese',
    name_en: 'Calzone Bolognese',
    name_tr: 'Bolonez Kalzone',
    name_ar: 'كالزوني بولونيز',
    description_nl: 'Met bolognesesaus en gorgonzola.',
    description_en: 'With bolognese sauce and gorgonzola.',
    description_tr: 'Bolonez sosu ve gorgonzola peyniri ile.',
    description_ar: 'مع صلصة البولونيز وجبن الغورغونزولا.',
    price: 10.00,
    image_url: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800',
    preparation_time: 22,
    vegetarian: false,
    seasonal: false,
    sold_out: false,
    allergens: { gluten: true, lactose: true },
    popular_count: 140,
    active: true,
  },
  {
    id: 'item-110',
    category_id: 'cat-16',
    name_nl: 'Calzone Speciaal',
    name_en: 'Calzone Special',
    name_tr: 'Özel Kalzone',
    name_ar: 'كالزوني سبيشيال',
    description_nl: 'Met döner en kipshoarma.',
    description_en: 'With döner and chicken shawarma.',
    description_tr: 'Döner ve tavuk şavarmalı.',
    description_ar: 'مع الدونر وشاورما الدجاج.',
    price: 10.00,
    image_url: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800',
    preparation_time: 22,
    vegetarian: false,
    seasonal: false,
    sold_out: false,
    allergens: { gluten: true, lactose: true },
    popular_count: 175,
    active: true,
  },
  {
    id: 'item-111',
    category_id: 'cat-16',
    name_nl: 'Calzone Rollo',
    name_en: 'Calzone Rollo',
    name_tr: 'Rulo Kalzone',
    name_ar: 'كالزوني رولو',
    description_nl: 'Met döner en ui.',
    description_en: 'With döner and onion.',
    description_tr: 'Döner ve soğanlı.',
    description_ar: 'مع الدونر والبصل.',
    price: 10.00,
    image_url: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800',
    preparation_time: 22,
    vegetarian: false,
    seasonal: false,
    sold_out: false,
    allergens: { gluten: true, lactose: true },
    popular_count: 150,
    active: true,
  },
  {
    id: 'item-112',
    category_id: 'cat-16',
    name_nl: 'Calzone Sucuk',
    name_en: 'Calzone Sucuk',
    name_tr: 'Sucuklu Kalzone',
    name_ar: 'كالزوني سجق',
    description_nl: 'Met gegrilde Turkse knoflookworst.',
    description_en: 'With grilled Turkish garlic sausage.',
    description_tr: 'Izgara Türk sucuğu ile.',
    description_ar: 'مع السجق التركي بالثوم المشوي.',
    price: 10.00,
    image_url: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800',
    preparation_time: 22,
    vegetarian: false,
    seasonal: false,
    sold_out: false,
    allergens: { gluten: true, lactose: true },
    popular_count: 135,
    active: true,
  },
  {
    id: 'item-113',
    category_id: 'cat-17',
    name_nl: 'Pasta Bolognese',
    name_en: 'Pasta Bolognese',
    name_tr: 'Bolonez Makarna',
    name_ar: 'باستا بولونيز',
    description_nl: 'Met bolognesesaus.',
    description_en: 'With bolognese sauce.',
    description_tr: 'Bolonez soslu.',
    description_ar: 'مع صلصة البولونيز.',
    price: 9.50,
    image_url: 'https://images.unsplash.com/photo-1551892374-ecf8754cf8b0?w=800',
    preparation_time: 18,
    vegetarian: false,
    seasonal: false,
    sold_out: false,
    allergens: { gluten: true, lactose: true },
    popular_count: 200,
    active: true,
  },
  {
    id: 'item-114',
    category_id: 'cat-17',
    name_nl: 'Pasta Siciliana',
    name_en: 'Pasta Siciliana',
    name_tr: 'Sisiliyana Makarna',
    name_ar: 'باستا صقلية',
    description_nl: 'Met diverse groenten, in tomatensaus.',
    description_en: 'With various vegetables, in tomato sauce.',
    description_tr: 'Çeşitli sebzeli, domates soslu.',
    description_ar: 'مع خضروات متنوعة في صلصة الطماطم.',
    price: 9.50,
    image_url: 'https://images.unsplash.com/photo-1551892374-ecf8754cf8b0?w=800',
    preparation_time: 18,
    vegetarian: true,
    seasonal: false,
    sold_out: false,
    allergens: { gluten: true, lactose: true },
    popular_count: 155,
    active: true,
  },
  {
    id: 'item-115',
    category_id: 'cat-17',
    name_nl: 'Pasta Carbonara',
    name_en: 'Pasta Carbonara',
    name_tr: 'Karbonara Makarna',
    name_ar: 'باستا كاربونارا',
    description_nl: 'Met spek en ei in roomsaus.',
    description_en: 'With bacon and egg in cream sauce.',
    description_tr: 'Kremamsı sosla pastırma ve yumurtalı.',
    description_ar: 'مع لحم الخنزير المقدد والبيض في صلصة الكريمة.',
    price: 9.50,
    image_url: 'https://images.unsplash.com/photo-1551892374-ecf8754cf8b0?w=800',
    preparation_time: 18,
    vegetarian: false,
    seasonal: false,
    sold_out: false,
    allergens: { gluten: true, lactose: true, eggs: true },
    popular_count: 220,
    active: true,
  },
  {
    id: 'item-116',
    category_id: 'cat-17',
    name_nl: 'Pasta Quattro Formaggi',
    name_en: 'Pasta Quattro Formaggi',
    name_tr: 'Dört Peynirli Makarna',
    name_ar: 'باستا أربعة جبن',
    description_nl: 'Met vier soorten kaas in roomsaus.',
    description_en: 'With four types of cheese in cream sauce.',
    description_tr: 'Kremamsı sosla dört çeşit peynirli.',
    description_ar: 'مع أربعة أنواع من الجبن في صلصة الكريمة.',
    price: 9.50,
    image_url: 'https://images.unsplash.com/photo-1551892374-ecf8754cf8b0?w=800',
    preparation_time: 18,
    vegetarian: true,
    seasonal: false,
    sold_out: false,
    allergens: { gluten: true, lactose: true },
    popular_count: 175,
    active: true,
  },
  {
    id: 'item-117',
    category_id: 'cat-17',
    name_nl: 'Pasta Tonno',
    name_en: 'Pasta Tonno',
    name_tr: 'Ton Balıklı Makarna',
    name_ar: 'باستا تونة',
    description_nl: 'Met tonijn in roomsaus.',
    description_en: 'With tuna in cream sauce.',
    description_tr: 'Kremamsı sosla ton balıklı.',
    description_ar: 'مع التونة في صلصة الكريمة.',
    price: 9.50,
    image_url: 'https://images.unsplash.com/photo-1551892374-ecf8754cf8b0?w=800',
    preparation_time: 18,
    vegetarian: false,
    seasonal: false,
    sold_out: false,
    allergens: { gluten: true, lactose: true, fish: true },
    popular_count: 145,
    active: true,
  },
  {
    id: 'item-118',
    category_id: 'cat-17',
    name_nl: 'Pasta Con Pollo',
    name_en: 'Pasta Con Pollo',
    name_tr: 'Tavuklu Makarna',
    name_ar: 'باستا بالدجاج',
    description_nl: 'Met kipfilet, paprika en ui in tomatensaus.',
    description_en: 'With chicken fillet, bell pepper and onion in tomato sauce.',
    description_tr: 'Domates sosunda tavuk fileto, biber ve soğanlı.',
    description_ar: 'مع فيليه الدجاج والفلفل والبصل في صلصة الطماطم.',
    price: 9.50,
    image_url: 'https://images.unsplash.com/photo-1551892374-ecf8754cf8b0?w=800',
    preparation_time: 18,
    vegetarian: false,
    seasonal: false,
    sold_out: false,
    allergens: { gluten: true, lactose: true },
    popular_count: 190,
    active: true,
  },
  {
    id: 'item-119',
    category_id: 'cat-17',
    name_nl: 'Lasagne al Forno',
    name_en: 'Lasagne al Forno',
    name_tr: 'Fırın Lazanya',
    name_ar: 'لازانيا بالفرن',
    description_nl: 'Deegbladen met bechamelsaus, kaas, tomaat, bolognesesaus en groenten.',
    description_en: 'Pasta sheets with béchamel sauce, cheese, tomato, bolognese sauce and vegetables.',
    description_tr: 'Beşamel sosu, peynir, domates, bolonez sosu ve sebzeli makarna tabakaları.',
    description_ar: 'صفائح عجين مع صلصة البيشاميل والجبن والطماطم وصلصة البولونيز والخضروات.',
    price: 9.50,
    image_url: 'https://images.unsplash.com/photo-1551892374-ecf8754cf8b0?w=800',
    preparation_time: 22,
    vegetarian: false,
    seasonal: false,
    sold_out: false,
    allergens: { gluten: true, lactose: true, eggs: true },
    popular_count: 210,
    active: true,
  },
  {
    id: 'item-120',
    category_id: 'cat-17',
    name_nl: 'Pasta Con Pollo Kipdoner',
    name_en: 'Pasta Con Pollo Chicken Döner',
    name_tr: 'Tavuk Dönerli Makarna',
    name_ar: 'باستا دونر دجاج',
    description_nl: 'Met kipdöner in saus.',
    description_en: 'With chicken döner in sauce.',
    description_tr: 'Soslu tavuk dönerli makarna.',
    description_ar: 'مع دونر الدجاج في الصلصة.',
    price: 9.50,
    image_url: 'https://images.unsplash.com/photo-1551892374-ecf8754cf8b0?w=800',
    preparation_time: 18,
    vegetarian: false,
    seasonal: false,
    sold_out: false,
    allergens: { gluten: true, lactose: true },
    popular_count: 165,
    active: true,
  },
  {
    id: 'item-121',
    category_id: 'cat-18',
    name_nl: 'Patat',
    name_en: 'Fries',
    name_tr: 'Patates',
    name_ar: 'بطاطا',
    description_nl: 'Knapperige frietjes.',
    description_en: 'Crispy fries.',
    description_tr: 'Çıtır patates kızartması.',
    description_ar: 'بطاطا مقلية مقرمشة.',
    price: 3.00,
    image_url: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=800',
    preparation_time: 8,
    vegetarian: true,
    seasonal: false,
    sold_out: false,
    allergens: {},
    popular_count: 350,
    active: true,
  },
  {
    id: 'item-122',
    category_id: 'cat-18',
    name_nl: 'Patat met Mayonaise',
    name_en: 'Fries with Mayonnaise',
    name_tr: 'Mayonezli Patates',
    name_ar: 'بطاطا مع مايونيز',
    description_nl: 'Knapperige frietjes met mayonaise.',
    description_en: 'Crispy fries with mayonnaise.',
    description_tr: 'Mayonezli çıtır patates kızartması.',
    description_ar: 'بطاطا مقلية مقرمشة مع المايونيز.',
    price: 3.50,
    image_url: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=800',
    preparation_time: 8,
    vegetarian: true,
    seasonal: false,
    sold_out: false,
    allergens: { eggs: true },
    popular_count: 310,
    active: true,
  },
  {
    id: 'item-123',
    category_id: 'cat-18',
    name_nl: 'Patat Groot',
    name_en: 'Large Fries',
    name_tr: 'Büyük Patates',
    name_ar: 'بطاطا كبيرة',
    description_nl: 'Grote portie knapperige frietjes.',
    description_en: 'Large portion of crispy fries.',
    description_tr: 'Büyük porsiyon çıtır patates kızartması.',
    description_ar: 'حصة كبيرة من البطاطا المقلية المقرمشة.',
    price: 4.00,
    image_url: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=800',
    preparation_time: 8,
    vegetarian: true,
    seasonal: false,
    sold_out: false,
    allergens: {},
    popular_count: 280,
    active: true,
  },
  {
    id: 'item-124',
    category_id: 'cat-18',
    name_nl: 'Patat Groot met Mayonaise',
    name_en: 'Large Fries with Mayonnaise',
    name_tr: 'Mayonezli Büyük Patates',
    name_ar: 'بطاطا كبيرة مع مايونيز',
    description_nl: 'Grote portie knapperige frietjes met mayonaise.',
    description_en: 'Large portion of crispy fries with mayonnaise.',
    description_tr: 'Mayonezli büyük porsiyon çıtır patates kızartması.',
    description_ar: 'حصة كبيرة من البطاطا المقلية المقرمشة مع المايونيز.',
    price: 4.50,
    image_url: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=800',
    preparation_time: 8,
    vegetarian: true,
    seasonal: false,
    sold_out: false,
    allergens: { eggs: true },
    popular_count: 260,
    active: true,
  },
  {
    id: 'item-125',
    category_id: 'cat-19',
    name_nl: 'Cola',
    name_en: 'Cola',
    name_tr: 'Kola',
    name_ar: 'كولا',
    description_nl: 'Blikje 330ml.',
    description_en: '330ml can.',
    description_tr: '330ml kutu.',
    description_ar: 'علبة 330 مل.',
    price: 3.00,
    image_url: 'https://images.unsplash.com/photo-1581636625402-29b2a704ef13?w=800',
    preparation_time: 1,
    vegetarian: true,
    seasonal: false,
    sold_out: false,
    allergens: {},
    popular_count: 400,
    active: true,
  },
  {
    id: 'item-126',
    category_id: 'cat-19',
    name_nl: 'Cola Zero',
    name_en: 'Cola Zero',
    name_tr: 'Kola Zero',
    name_ar: 'كولا زيرو',
    description_nl: 'Blikje 330ml.',
    description_en: '330ml can.',
    description_tr: '330ml kutu.',
    description_ar: 'علبة 330 مل.',
    price: 3.00,
    image_url: 'https://images.unsplash.com/photo-1581636625402-29b2a704ef13?w=800',
    preparation_time: 1,
    vegetarian: true,
    seasonal: false,
    sold_out: false,
    allergens: {},
    popular_count: 280,
    active: true,
  },
  {
    id: 'item-127',
    category_id: 'cat-19',
    name_nl: 'Fanta',
    name_en: 'Fanta',
    name_tr: 'Fanta',
    name_ar: 'فانتا',
    description_nl: 'Blikje 330ml.',
    description_en: '330ml can.',
    description_tr: '330ml kutu.',
    description_ar: 'علبة 330 مل.',
    price: 3.00,
    image_url: 'https://images.unsplash.com/photo-1581636625402-29b2a704ef13?w=800',
    preparation_time: 1,
    vegetarian: true,
    seasonal: false,
    sold_out: false,
    allergens: {},
    popular_count: 250,
    active: true,
  },
  {
    id: 'item-128',
    category_id: 'cat-19',
    name_nl: 'Fanta Exotic (330ml)',
    name_en: 'Fanta Exotic (330ml)',
    name_tr: 'Fanta Egzotik (330ml)',
    name_ar: 'فانتا إكزوتيك (330 مل)',
    description_nl: 'Blikje 330ml.',
    description_en: '330ml can.',
    description_tr: '330ml kutu.',
    description_ar: 'علبة 330 مل.',
    price: 3.00,
    image_url: 'https://images.unsplash.com/photo-1581636625402-29b2a704ef13?w=800',
    preparation_time: 1,
    vegetarian: true,
    seasonal: false,
    sold_out: false,
    allergens: {},
    popular_count: 190,
    active: true,
  },
  {
    id: 'item-129',
    category_id: 'cat-19',
    name_nl: 'Cassis',
    name_en: 'Cassis',
    name_tr: 'Kazis',
    name_ar: 'كاسيس',
    description_nl: 'Blikje 330ml.',
    description_en: '330ml can.',
    description_tr: '330ml kutu.',
    description_ar: 'علبة 330 مل.',
    price: 3.00,
    image_url: 'https://images.unsplash.com/photo-1581636625402-29b2a704ef13?w=800',
    preparation_time: 1,
    vegetarian: true,
    seasonal: false,
    sold_out: false,
    allergens: {},
    popular_count: 160,
    active: true,
  },
  {
    id: 'item-130',
    category_id: 'cat-19',
    name_nl: 'Sprite',
    name_en: 'Sprite',
    name_tr: 'Sprite',
    name_ar: 'سبرايت',
    description_nl: 'Blikje 330ml.',
    description_en: '330ml can.',
    description_tr: '330ml kutu.',
    description_ar: 'علبة 330 مل.',
    price: 3.00,
    image_url: 'https://images.unsplash.com/photo-1581636625402-29b2a704ef13?w=800',
    preparation_time: 1,
    vegetarian: true,
    seasonal: false,
    sold_out: false,
    allergens: {},
    popular_count: 210,
    active: true,
  },
  {
    id: 'item-131',
    category_id: 'cat-19',
    name_nl: 'Ayran',
    name_en: 'Ayran',
    name_tr: 'Ayran',
    name_ar: 'عيران',
    description_nl: 'Traditioneel Turks yoghurtdrankje.',
    description_en: 'Traditional Turkish yoghurt drink.',
    description_tr: 'Geleneksel Türk yoğurt içeceği.',
    description_ar: 'مشروب الزبادي التركي التقليدي.',
    price: 2.50,
    image_url: 'https://images.unsplash.com/photo-1541167760496-1628856ab772?w=800',
    preparation_time: 1,
    vegetarian: true,
    seasonal: false,
    sold_out: false,
    allergens: { lactose: true },
    popular_count: 300,
    active: true,
  },
  {
    id: 'item-132',
    category_id: 'cat-19',
    name_nl: 'Chaudfontaine Blauw',
    name_en: 'Chaudfontaine Still',
    name_tr: 'Chaudfontaine Su',
    name_ar: 'ماء شوفونتين',
    description_nl: 'Plat mineraalwater.',
    description_en: 'Still mineral water.',
    description_tr: 'Doğal mineralli su.',
    description_ar: 'مياه معدنية.',
    price: 3.00,
    image_url: 'https://images.unsplash.com/photo-1581636625402-29b2a704ef13?w=800',
    preparation_time: 1,
    vegetarian: true,
    seasonal: false,
    sold_out: false,
    allergens: {},
    popular_count: 180,
    active: true,
  },
  {
    id: 'item-133',
    category_id: 'cat-19',
    name_nl: 'AA Drink',
    name_en: 'AA Drink',
    name_tr: 'AA İçeceği',
    name_ar: 'مشروب AA',
    description_nl: 'Sportdrank.',
    description_en: 'Sports drink.',
    description_tr: 'Spor içeceği.',
    description_ar: 'مشروب رياضي.',
    price: 3.00,
    image_url: 'https://images.unsplash.com/photo-1581636625402-29b2a704ef13?w=800',
    preparation_time: 1,
    vegetarian: true,
    seasonal: false,
    sold_out: false,
    allergens: {},
    popular_count: 140,
    active: true,
  },
  {
    id: 'item-134',
    category_id: 'cat-19',
    name_nl: 'Fernandes Blauw',
    name_en: 'Fernandes Blue',
    name_tr: 'Fernandes Mavi',
    name_ar: 'فيرناندس أزرق',
    description_nl: 'Blikje 330ml.',
    description_en: '330ml can.',
    description_tr: '330ml kutu.',
    description_ar: 'علبة 330 مل.',
    price: 3.00,
    image_url: 'https://images.unsplash.com/photo-1581636625402-29b2a704ef13?w=800',
    preparation_time: 1,
    vegetarian: true,
    seasonal: false,
    sold_out: false,
    allergens: {},
    popular_count: 150,
    active: true,
  },
  {
    id: 'item-135',
    category_id: 'cat-19',
    name_nl: 'Fernandes Rood',
    name_en: 'Fernandes Red',
    name_tr: 'Fernandes Kırmızı',
    name_ar: 'فيرناندس أحمر',
    description_nl: 'Blikje 330ml.',
    description_en: '330ml can.',
    description_tr: '330ml kutu.',
    description_ar: 'علبة 330 مل.',
    price: 3.00,
    image_url: 'https://images.unsplash.com/photo-1581636625402-29b2a704ef13?w=800',
    preparation_time: 1,
    vegetarian: true,
    seasonal: false,
    sold_out: false,
    allergens: {},
    popular_count: 145,
    active: true,
  },
  {
    id: 'item-136',
    category_id: 'cat-19',
    name_nl: 'Lipton Ice Tea Green (330ml)',
    name_en: 'Lipton Ice Tea Green (330ml)',
    name_tr: 'Lipton Yeşil Soğuk Çay (330ml)',
    name_ar: 'ليبتون شاي أخضر مثلج (330 مل)',
    description_nl: 'Blikje 330ml.',
    description_en: '330ml can.',
    description_tr: '330ml kutu.',
    description_ar: 'علبة 330 مل.',
    price: 3.00,
    image_url: 'https://images.unsplash.com/photo-1581636625402-29b2a704ef13?w=800',
    preparation_time: 1,
    vegetarian: true,
    seasonal: false,
    sold_out: false,
    allergens: {},
    popular_count: 170,
    active: true,
  },
  {
    id: 'item-137',
    category_id: 'cat-19',
    name_nl: 'Lipton Ice Tea Sparkling (330ml)',
    name_en: 'Lipton Ice Tea Sparkling (330ml)',
    name_tr: 'Lipton Köpüklü Soğuk Çay (330ml)',
    name_ar: 'ليبتون شاي مثلج فوار (330 مل)',
    description_nl: 'Blikje 330ml.',
    description_en: '330ml can.',
    description_tr: '330ml kutu.',
    description_ar: 'علبة 330 مل.',
    price: 3.25,
    image_url: 'https://images.unsplash.com/photo-1581636625402-29b2a704ef13?w=800',
    preparation_time: 1,
    vegetarian: true,
    seasonal: false,
    sold_out: false,
    allergens: {},
    popular_count: 155,
    active: true,
  },
  {
    id: 'item-138',
    category_id: 'cat-19',
    name_nl: 'Red Bull',
    name_en: 'Red Bull',
    name_tr: 'Red Bull',
    name_ar: 'ريد بول',
    description_nl: 'Energiedrank 250ml.',
    description_en: 'Energy drink 250ml.',
    description_tr: 'Enerji içeceği 250ml.',
    description_ar: 'مشروب طاقة 250 مل.',
    price: 3.50,
    image_url: 'https://images.unsplash.com/photo-1581636625402-29b2a704ef13?w=800',
    preparation_time: 1,
    vegetarian: true,
    seasonal: false,
    sold_out: false,
    allergens: {},
    popular_count: 200,
    active: true,
  },
  {
    id: 'item-139',
    category_id: 'cat-20',
    name_nl: 'Knoflooksaus',
    name_en: 'Garlic Sauce',
    name_tr: 'Sarımsaklı Sos',
    name_ar: 'صلصة الثوم',
    description_nl: 'Bakje knoflooksaus.',
    description_en: 'Cup of garlic sauce.',
    description_tr: 'Sarımsaklı sos.',
    description_ar: 'كوب صلصة الثوم.',
    price: 0.25,
    image_url: 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=800',
    preparation_time: 1,
    vegetarian: true,
    seasonal: false,
    sold_out: false,
    allergens: { eggs: true },
    popular_count: 500,
    active: true,
  },
  {
    id: 'item-140',
    category_id: 'cat-20',
    name_nl: 'Sambal',
    name_en: 'Sambal',
    name_tr: 'Sambal',
    name_ar: 'سمبل',
    description_nl: 'Bakje sambal.',
    description_en: 'Cup of sambal.',
    description_tr: 'Sambal sosu.',
    description_ar: 'كوب سمبل.',
    price: 0.25,
    image_url: 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=800',
    preparation_time: 1,
    vegetarian: true,
    seasonal: false,
    sold_out: false,
    allergens: {},
    popular_count: 350,
    active: true,
  },
  {
    id: 'item-141',
    category_id: 'cat-20',
    name_nl: 'Mayonaise',
    name_en: 'Mayonnaise',
    name_tr: 'Mayonez',
    name_ar: 'مايونيز',
    description_nl: 'Bakje mayonaise.',
    description_en: 'Cup of mayonnaise.',
    description_tr: 'Mayonez.',
    description_ar: 'كوب مايونيز.',
    price: 0.25,
    image_url: 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=800',
    preparation_time: 1,
    vegetarian: true,
    seasonal: false,
    sold_out: false,
    allergens: { eggs: true },
    popular_count: 420,
    active: true,
  },
  {
    id: 'item-142',
    category_id: 'cat-20',
    name_nl: 'Whiskeysaus',
    name_en: 'Whiskey Sauce',
    name_tr: 'Viski Sosu',
    name_ar: 'صلصة الويسكي',
    description_nl: 'Bakje whiskeysaus.',
    description_en: 'Cup of whiskey sauce.',
    description_tr: 'Viski sosu.',
    description_ar: 'كوب صلصة الويسكي.',
    price: 0.25,
    image_url: 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=800',
    preparation_time: 1,
    vegetarian: true,
    seasonal: false,
    sold_out: false,
    allergens: { lactose: true },
    popular_count: 280,
    active: true,
  },
  {
    id: 'item-143',
    category_id: 'cat-20',
    name_nl: 'Bakje Rijst',
    name_en: 'Side of Rice',
    name_tr: 'Yanında Pirinç',
    name_ar: 'طبق أرز جانبي',
    description_nl: 'Portie basmatirijst.',
    description_en: 'Portion of basmati rice.',
    description_tr: 'Porsiyon basmati pirinç.',
    description_ar: 'حصة أرز بسمتي.',
    price: 3.50,
    image_url: 'https://images.unsplash.com/photo-1536304929831-ee1ca9d44906?w=800',
    preparation_time: 5,
    vegetarian: true,
    seasonal: false,
    sold_out: false,
    allergens: {},
    popular_count: 260,
    active: true,
  },
  {
    id: 'item-144',
    category_id: 'cat-20',
    name_nl: 'Bakje Döner Klein',
    name_en: 'Small Döner Box',
    name_tr: 'Küçük Döner Kutusu',
    name_ar: 'علبة دونر صغيرة',
    description_nl: 'Klein bakje döner.',
    description_en: 'Small box of döner.',
    description_tr: 'Küçük kutu döner.',
    description_ar: 'علبة صغيرة من الدونر.',
    price: 7.00,
    image_url: 'https://images.unsplash.com/photo-1529006557810-274b9b2fc783?w=800',
    preparation_time: 8,
    vegetarian: false,
    seasonal: false,
    sold_out: false,
    allergens: { gluten: true },
    popular_count: 190,
    active: true,
  },
  {
    id: 'item-145',
    category_id: 'cat-20',
    name_nl: 'Bakje Döner Groot',
    name_en: 'Large Döner Box',
    name_tr: 'Büyük Döner Kutusu',
    name_ar: 'علبة دونر كبيرة',
    description_nl: 'Groot bakje döner.',
    description_en: 'Large box of döner.',
    description_tr: 'Büyük kutu döner.',
    description_ar: 'علبة كبيرة من الدونر.',
    price: 14.00,
    image_url: 'https://images.unsplash.com/photo-1529006557810-274b9b2fc783?w=800',
    preparation_time: 8,
    vegetarian: false,
    seasonal: false,
    sold_out: false,
    allergens: { gluten: true },
    popular_count: 150,
    active: true,
  },
  {
    id: 'item-146',
    category_id: 'cat-20',
    name_nl: 'Bakje Kipdöner Klein',
    name_en: 'Small Chicken Döner Box',
    name_tr: 'Küçük Tavuk Döner Kutusu',
    name_ar: 'علبة دونر دجاج صغيرة',
    description_nl: 'Klein bakje kipdöner.',
    description_en: 'Small box of chicken döner.',
    description_tr: 'Küçük kutu tavuk döner.',
    description_ar: 'علبة صغيرة من دونر الدجاج.',
    price: 7.00,
    image_url: 'https://images.unsplash.com/photo-1529006557810-274b9b2fc783?w=800',
    preparation_time: 8,
    vegetarian: false,
    seasonal: false,
    sold_out: false,
    allergens: { gluten: true },
    popular_count: 175,
    active: true,
  },
  {
    id: 'item-147',
    category_id: 'cat-20',
    name_nl: 'Bakje Kipdöner Groot',
    name_en: 'Large Chicken Döner Box',
    name_tr: 'Büyük Tavuk Döner Kutusu',
    name_ar: 'علبة دونر دجاج كبيرة',
    description_nl: 'Groot bakje kipdöner.',
    description_en: 'Large box of chicken döner.',
    description_tr: 'Büyük kutu tavuk döner.',
    description_ar: 'علبة كبيرة من دونر الدجاج.',
    price: 14.00,
    image_url: 'https://images.unsplash.com/photo-1529006557810-274b9b2fc783?w=800',
    preparation_time: 8,
    vegetarian: false,
    seasonal: false,
    sold_out: false,
    allergens: { gluten: true },
    popular_count: 140,
    active: true,
  },
  {
    id: 'item-148',
    category_id: 'cat-20',
    name_nl: 'Los Brood',
    name_en: 'Bread Roll',
    name_tr: 'Ekmek',
    name_ar: 'خبز',
    description_nl: 'Los broodje.',
    description_en: 'Bread roll.',
    description_tr: 'Ekmek.',
    description_ar: 'خبز.',
    price: 0.75,
    image_url: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800',
    preparation_time: 1,
    vegetarian: true,
    seasonal: false,
    sold_out: false,
    allergens: { gluten: true },
    popular_count: 220,
    active: true,
  },
  {
    id: 'item-149',
    category_id: 'cat-20',
    name_nl: 'Turks Brood',
    name_en: 'Turkish Bread',
    name_tr: 'Türk Ekmeği',
    name_ar: 'خبز تركي',
    description_nl: 'Vers Turks brood.',
    description_en: 'Fresh Turkish bread.',
    description_tr: 'Taze Türk ekmeği.',
    description_ar: 'خبز تركي طازج.',
    price: 4.00,
    image_url: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800',
    preparation_time: 5,
    vegetarian: true,
    seasonal: false,
    sold_out: false,
    allergens: { gluten: true },
    popular_count: 195,
    active: true,
  },
]

import type { Addon } from './types'
export const seedAddons: Addon[] = []

export const seedOpeningHours = [
  { id: 'oh-0', day_of_week: 0, open_time: '16:00', close_time: '22:00', delivery_start: '16:30', delivery_end: '21:30', closed: false },
  { id: 'oh-1', day_of_week: 1, open_time: '16:00', close_time: '22:00', delivery_start: '16:30', delivery_end: '21:30', closed: false },
  { id: 'oh-2', day_of_week: 2, open_time: '16:00', close_time: '22:00', delivery_start: '16:30', delivery_end: '21:30', closed: false },
  { id: 'oh-3', day_of_week: 3, open_time: '16:00', close_time: '22:00', delivery_start: '16:30', delivery_end: '21:30', closed: false },
  { id: 'oh-4', day_of_week: 4, open_time: '16:00', close_time: '22:30', delivery_start: '16:30', delivery_end: '22:00', closed: false },
  { id: 'oh-5', day_of_week: 5, open_time: '14:00', close_time: '23:00', delivery_start: '14:30', delivery_end: '22:30', closed: false },
  { id: 'oh-6', day_of_week: 6, open_time: '14:00', close_time: '22:30', delivery_start: '14:30', delivery_end: '22:00', closed: false },
]

export const seedCoupons = [
  { id: 'coupon-1', code: 'MOZAIK10', type: 'percentage', value: 10, min_order: 15, max_uses: 1000, uses_count: 0, valid_from: '2024-01-01', valid_until: '2025-12-31', active: true },
]

export const seedChallenges = [
  {
    id: 'challenge-1',
    title_nl: 'Weekend Warrior',
    title_en: 'Weekend Warrior',
    title_tr: 'Hafta Sonu Savaşçısı',
    title_ar: 'محارب نهاية الأسبوع',
    description_nl: 'Bestel 3x dit weekend en verdien 50 bonuspunten!',
    target_count: 3,
    points_reward: 50,
    start_date: '2024-06-01',
    end_date: '2024-12-31',
    active: true,
  },
]

export const seedBadges = [
  { id: 'badge-1', name: 'Eerste bestelling', icon: '🎉', description: 'Je eerste bestelling bij Mr. Mozaik!', condition_type: 'orders', condition_value: 1 },
  { id: 'badge-2', name: 'Trouwe klant', icon: '⭐', description: '10 bestellingen geplaatst', condition_type: 'orders', condition_value: 10 },
  { id: 'badge-3', name: 'Shoarma Fan', icon: '🥙', description: '5x shoarma besteld', condition_type: 'category', condition_value: 5 },
]
